// webauthn-verify-reg — verifies the WebAuthn attestation response from
// navigator.credentials.create() and stores the credential. Requires
// authentication. After storing, sets webauthn_enabled=true on the user.

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { verifyRegistrationResponse } from 'npm:@simplewebauthn/server@10';
import { verifySignedChallenge, getRpConfig, uint8ArrayToBase64Url } from '../../shared/webauthn.ts';

export default async function (req: Request): Promise<Response> {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const rpConfig = getRpConfig(req);
    if (!rpConfig) return Response.json({ error: 'Could not determine origin' }, { status: 400 });

    const body = await req.json().catch(() => ({}));
    const { attestation, challenge, challenge_signature, label } = body;
    if (!attestation || !challenge || !challenge_signature) {
      return Response.json({ error: 'Missing attestation or challenge' }, { status: 400 });
    }

    // Verify the challenge was generated by this server (stateless CSRF protection)
    const valid = await verifySignedChallenge(
      process.env.BACKEND_FUNCTION_SECRET!,
      challenge,
      challenge_signature,
    );
    if (!valid) return Response.json({ error: 'Invalid or expired challenge' }, { status: 403 });

    const verification = await verifyRegistrationResponse({
      response: attestation,
      expectedChallenge: challenge,
      expectedOrigin: rpConfig.origin,
      expectedRPID: rpConfig.rpId,
    });

    if (!verification.verified || !verification.registrationInfo) {
      return Response.json({ error: 'Registration verification failed' }, { status: 400 });
    }

    const { credentialID, credentialPublicKey, counter, credentialDeviceType, credentialBackedUp } =
      verification.registrationInfo;

    const credentialIdB64 = credentialID; // already base64url from @simplewebauthn/server
    const pubKeyB64 = uint8ArrayToBase64Url(credentialPublicKey);

    // Check for duplicate credential ID — if already registered, link it to
    // the wallet (if not already) and return success instead of a 409 error.
    const dupes = await base44.asServiceRole.entities.WebAuthnCredential
      .filter({ credential_id: credentialIdB64 }, '-created_date', 1)
      .catch(() => []);
    if (dupes && dupes.length) {
      const userDid = user.data?.did || user.did;
      if (userDid) {
        const wallets = await base44.asServiceRole.entities.CustodialWallet
          .filter({ did: userDid, active: true }, '-created_date', 1)
          .catch(() => []);
        if (wallets && wallets.length) {
          const wallet = wallets[0];
          if (!(wallet.passkey_credential_ids || []).includes(credentialIdB64)) {
            await base44.asServiceRole.entities.CustodialWallet.update(wallet.id, {
              passkey_credential_ids: [...(wallet.passkey_credential_ids || []), credentialIdB64],
              has_passkey: true,
            }).catch(() => {});
          }
        }
      }
      return Response.json({
        verified: true,
        credential_id: credentialIdB64,
        label: label || 'Security Key',
        already_registered: true,
      });
    }

    await base44.asServiceRole.entities.WebAuthnCredential.create({
      credential_id: credentialIdB64,
      public_key: pubKeyB64,
      counter,
      transports: attestation.response?.transports || [],
      label: label || 'Security Key',
      user_id: user.id,
      email: user.email,
      created_at: new Date().toISOString(),
    });

    // Mark user as having WebAuthn enabled
    await base44.asServiceRole.entities.User.update(user.id, { webauthn_enabled: true });

    // Unify: also add this credential to the user's active CustodialWallet
    // (if any) so one passkey serves both account login and wallet unlock.
    const userDid = user.data?.did || user.did;
    if (userDid) {
      const wallets = await base44.asServiceRole.entities.CustodialWallet
        .filter({ did: userDid, active: true }, '-created_date', 1)
        .catch(() => []);
      if (wallets && wallets.length) {
        const wallet = wallets[0];
        const updatedCredentialIds = [...(wallet.passkey_credential_ids || []), credentialIdB64];
        await base44.asServiceRole.entities.CustodialWallet.update(wallet.id, {
          passkey_credential_ids: updatedCredentialIds,
          has_passkey: true,
        }).catch(() => {});
      }
    }

    return Response.json({
      verified: true,
      credential_id: credentialIdB64,
      label: label || 'Security Key',
    });
  } catch (error: any) {
    console.error('webauthn-verify-reg error:', error?.message || error);
    return Response.json({ error: error?.message || 'Internal error' }, { status: 500 });
  }
}