// add-wallet-passkey — registers a new WebAuthn passkey for wallet unlock.
// Handles two phases via the `phase` body parameter:
//   phase: 'options'  → returns registration options (excluding existing wallet passkeys)
//   phase: 'verify'    → verifies the attestation, stores the credential in
//                       WebAuthnCredential, and appends the credential ID to
//                       the wallet's passkey_credential_ids + sets has_passkey=true

import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import {
  generateRegistrationOptions,
  verifyRegistrationResponse,
} from 'npm:@simplewebauthn/server@10';
import { generateSignedChallenge, verifySignedChallenge, getRpConfig } from '../../shared/webauthn.ts';

export default async function (req: Request): Promise<Response> {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const did = user.did;
    if (!did) return Response.json({ error: 'No DID found' }, { status: 400 });

    const body = await req.json().catch(() => ({}));
    const phase = body.phase || 'options';

    // Find the user's active custodial wallet
    const wallets = await base44.entities.CustodialWallet.filter({ did, active: true });
    if (!wallets.length) {
      return Response.json({ error: 'No custodial wallet found. Create a wallet first.' }, { status: 404 });
    }
    const wallet = wallets[0];

    const rpConfig = getRpConfig(req);
    if (!rpConfig) return Response.json({ error: 'Could not determine origin' }, { status: 400 });

    if (phase === 'options') {
      // Exclude existing wallet passkeys
      const excludeCredentials = (wallet.passkey_credential_ids || []).map((id: string) => ({
        id,
        type: 'public-key' as const,
      }));

      const { challenge, signature } = await generateSignedChallenge(process.env.BACKEND_FUNCTION_SECRET!);

      const options = await generateRegistrationOptions({
        rpName: 'SwapPulse Wallet',
        rpID: rpConfig.rpId,
        userID: user.id,
        userName: user.email || user.id,
        challenge,
        excludeCredentials,
        authenticatorSelection: {
          residentKey: 'preferred',
          userVerification: 'preferred',
        },
        supportedAlgorithmIDs: [-7, -257],
      });

      return Response.json({ options, challenge, challenge_signature: signature });
    }

    if (phase === 'verify') {
      const { attestation, challenge, challenge_signature, label } = body;
      if (!attestation || !challenge || !challenge_signature) {
        return Response.json({ error: 'Missing attestation or challenge' }, { status: 400 });
      }

      // Verify the challenge was generated by this server
      const valid = await verifySignedChallenge(
        process.env.BACKEND_FUNCTION_SECRET!,
        challenge,
        challenge_signature,
      );
      if (!valid) return Response.json({ error: 'Invalid or expired challenge' }, { status: 403 });

      const verification = await verifyRegistrationResponse({
        response: attestation,
        expectedChallenge: challenge,
        expectedOrigin: rpConfig.origin,
        expectedRPID: rpConfig.rpId,
      });

      if (!verification.verified || !verification.registrationInfo) {
        return Response.json({ error: 'Registration verification failed' }, { status: 400 });
      }

      const { credentialID, credentialPublicKey, counter, transports } = verification.registrationInfo;

      // Check for duplicate credential ID
      const dupes = await base44.asServiceRole.entities.WebAuthnCredential
        .filter({ credential_id: credentialID }, '-created_date', 1)
        .catch(() => []);
      if (dupes && dupes.length) {
        return Response.json({ error: 'This security key is already registered' }, { status: 409 });
      }

      // Store the credential in WebAuthnCredential (reused for verification)
      await base44.asServiceRole.entities.WebAuthnCredential.create({
        credential_id: credentialID,
        public_key: credentialPublicKey,
        counter,
        transports: transports || [],
        label: label || 'Wallet Key',
        user_id: user.id,
        email: user.email,
        created_at: new Date().toISOString(),
      });

      // Append the credential ID to the wallet's passkey list
      const updatedCredentialIds = [...(wallet.passkey_credential_ids || []), credentialID];
      await base44.entities.CustodialWallet.update(wallet.id, {
        passkey_credential_ids: updatedCredentialIds,
        has_passkey: true,
      });

      return Response.json({
        verified: true,
        credential_id: credentialID,
        label: label || 'Wallet Key',
      });
    }

    return Response.json({ error: 'Invalid phase. Use "options" or "verify".' }, { status: 400 });
  } catch (error: any) {
    console.error('add-wallet-passkey error:', error?.message || error);
    return Response.json({ error: error?.message || 'Internal error' }, { status: 500 });
  }
}