// English UI strings extracted from src/lib/i18n/translations/en.js
// Used by the translate-ui-strings backend function as the source for AI translation.

export const UI_STRINGS_EN: Record<string, string> = {
  'nav.home': 'Home', 'nav.explore': 'Explore', 'nav.collection': 'Collection', 'nav.scan': 'Scan Cards',
  'nav.binders': 'Binders', 'nav.trades': 'Trade Board', 'nav.circles': 'Circles', 'nav.meetups': 'Meetups',
  'nav.live': 'Live Now', 'nav.notifications': 'Notifications', 'nav.messages': 'Messages', 'nav.more': 'More',
  'nav.trust': 'Trust', 'nav.whoToFollow': 'Who to Follow', 'nav.achievements': 'Achievements',
  'nav.challenges': 'Challenges', 'nav.packParties': 'Pack Parties', 'nav.pullOfTheWeek': 'Pull of the Week',
  'nav.packOpenings': 'Pack Openings', 'nav.market': 'Market Watch', 'nav.predictions': 'Predictions',
  'nav.grading': 'Grading', 'nav.help': 'Help & Info', 'nav.donate': 'Donate', 'nav.settings': 'Settings',
  'nav.login': 'Log in', 'nav.logout': 'Log Out', 'nav.profile': 'View profile', 'nav.admin': 'Admin',
  'nav.moderation': 'Moderation',
  'card.overview': 'Overview', 'card.discussion': 'Discussion', 'card.posts': 'Posts', 'card.reviews': 'Reviews',
  'card.trades': 'Trades', 'card.packOpenings': 'Pack Openings', 'card.addToCollection': 'Add to Collection',
  'card.wishlist': 'Wishlist', 'card.listForTrade': 'List for Trade', 'card.priceAlert': 'Price Alert',
  'card.marketPrice': 'Market Price', 'card.variants': 'Variants', 'card.weaknessResistance': 'Weakness & Resistance',
  'card.legality': 'Legality', 'card.standardLegal': 'Standard-legal', 'card.notExpanded': 'Not Expanded-legal',
  'card.attacks': 'Attacks', 'card.abilities': 'Abilities', 'card.hp': 'HP', 'card.stage': 'Stage',
  'card.evolvesFrom': 'Evolves from', 'card.illustrator': 'Illustrator', 'card.retreat': 'Retreat',
  'card.regulationMark': 'Regulation Mark', 'card.avgMarket': 'avg market', 'card.source': 'Source',
  'card.normal': 'Normal', 'card.holo': 'Holo', 'card.reverse': 'Reverse', 'card.firstEdition': '1st Edition',
  'card.promo': 'Promo', 'card.notFound': 'Card not found.', 'card.loading': 'Loading…',
  'card.weakness': 'Weakness', 'card.resistance': 'Resistance',
  'common.loading': 'Loading…', 'common.search': 'Search', 'common.follow': 'Follow', 'common.following': 'Following',
  'common.reply': 'Reply', 'common.repost': 'Repost', 'common.like': 'Like', 'common.share': 'Share',
  'common.cancel': 'Cancel', 'common.save': 'Save', 'common.delete': 'Delete', 'common.edit': 'Edit',
  'common.close': 'Close', 'common.viewOnSwapPulse': 'View on SwapPulse', 'common.fromBluesky': 'From Bluesky',
  'common.viewAll': 'View all', 'common.noResults': 'No results yet', 'common.collectors': 'collectors',
  'feed.forYou': 'For You', 'feed.freshPulls': 'Fresh Pulls', 'feed.tradeFloor': 'Trade Floor',
  'feed.showcase': 'Showcase', 'feed.quiet': 'Your feed is quiet', 'feed.followCollectors': 'Follow collectors to personalize your feed',
  'feed.discoverCollectors': 'Discover collectors', 'feed.welcome': 'Welcome to SwapPulse',
  'feed.createAccount': 'Create account', 'feed.exploreCards': 'Explore cards',
  'trending.title': 'Trending Cards', 'trending.subtitle': 'Most talked-about cards right now',
  'trending.posts': 'posts', 'lang.switch': 'Language', 'lang.interface': 'Interface language',
  'nav.terms': 'Terms', 'nav.privacy': 'Privacy', 'nav.status': 'Status',
  'feed.quietSub': 'Follow some collectors to fill your feed.',
  'feed.followCollectorsSub': "You're seeing recent posts from the community. Follow collectors to see their content first.",
  'feed.noPosts': 'No posts in this feed yet. Check back soon!',
  'feed.welcomeSub': 'Join the decentralized social network for Pokémon TCG collectors, track your collection, trade cards, and connect with the community.',
  'page.binders.title': 'Digital Binders', 'page.binders.subtitle': 'Curated showcases of prized cards',
  'page.binders.myBinders': 'My Binders', 'page.binders.discover': 'Discover', 'page.binders.new': 'New',
  'page.binders.empty.mine': 'No binders yet', 'page.binders.empty.discover': 'Nothing to discover yet',
  'page.binders.empty.mineSub': 'Create your first digital binder.',
  'page.binders.empty.discoverSub': 'Public binders from the community will appear here.',
  'page.binders.create': 'Create Binder',
  'page.collection.title': 'My Collection', 'page.collection.cardsTracked': 'cards tracked', 'page.collection.add': 'Add',
  'page.collection.tabs.cards': 'All Cards', 'page.collection.tabs.completion': 'Completion', 'page.collection.tabs.duplicates': 'Duplicates',
  'page.collection.tabs.binder': 'Binder', 'page.collection.tabs.analytics': 'Analytics', 'page.collection.tabs.importExport': 'Import / Export', 'page.collection.tabs.insurance': 'Insurance',
  'page.collection.stats.totalValue': 'Total Value', 'page.collection.stats.cards': 'Cards', 'page.collection.stats.showcased': 'Showcased',
  'page.market.title': 'Market Watch', 'page.market.subtitle': 'Track prices and your portfolio', 'page.market.sync': 'Sync now',
  'page.explore.title': 'Explore', 'page.explore.subtitle': 'Search the Pokémon TCG catalogue',
  'page.explore.cards': 'Cards', 'page.explore.people': 'People', 'page.explore.posts': 'Posts',
  'page.trades.title': 'Trade Board', 'page.trades.subtitle': 'Open trade listings', 'page.trades.newListing': 'New Listing',
  'page.trades.empty': 'No active trades', 'page.trades.emptySub': 'Create a listing to start trading.',
  'footer.tagline': 'A decentralized Pokémon TCG community',
  'footer.terms': 'Terms', 'footer.privacy': 'Privacy Policy', 'footer.help': 'Help', 'footer.status': 'Status', 'footer.explore': 'Explore', 'footer.donate': 'Donate',
  'footer.disclaimer': 'SwapPulse is a free, open-source platform. Pokémon and Pokémon TCG are trademarks of Nintendo, Game Freak, and The Pokémon Company. SwapPulse is not affiliated with or endorsed by them.',
  'footer.builtOn': '© SwapPulse - Built on the AT Protocol · Powered by TCGdex',
  'page.sets.title': 'Set Checklists', 'page.sets.subtitle': 'Track completion and download printable PDFs',
  'page.sets.signIn': 'Sign in to track your collection', 'page.sets.signInSub': 'You need a SwapPulse account to manage your set checklists and download PDFs.',
  'profile.tab.posts': 'Posts', 'profile.tab.activity': 'Activity', 'profile.tab.binder': 'Binder', 'profile.tab.collection': 'Collection',
  'profile.tab.trades': 'Trades', 'profile.tab.tradeActivity': 'Trade Activity', 'profile.tab.reputation': 'Reputation', 'profile.tab.following': 'Following',
  'profile.tab.journals': 'Journals', 'profile.tab.podcasts': 'Podcasts', 'profile.tab.crossPosting': 'Cross-Posting', 'profile.tab.privacy': 'Privacy',
  'page.trust.title': 'Trust & Vouches', 'page.trust.yourScore': 'Your Trust Score', 'page.trust.scoreSub': 'Based on incoming vouches from trusted collectors.',
  'page.trust.vouches': 'vouches', 'page.trust.mutual': 'mutual',
  'page.notifications.title': 'Notifications', 'page.notifications.subtitle': 'Trade matches, price drops and activity from across SwapPulse',
  'page.notifications.markAllRead': 'Mark all read', 'page.notifications.emptySub': 'Trade matches and price alerts will show up here.',
  'page.notifications.empty.all': 'No notifications yet', 'page.notifications.empty.unread': 'No unread notifications',
  'page.notifications.empty.mentions': 'No mentions', 'page.notifications.empty.follows': 'No new follows',
  'common.today': 'Today', 'common.earlier': 'Earlier', 'common.quote': 'Quote', 'common.report': 'Report', 'common.collector': 'Collector',
  'post.type.packPull': 'Pack Pull', 'post.type.trade': 'Trade', 'post.type.showcase': 'Showcase',
  'page.settings.title': 'Settings', 'page.settings.subtitle': 'Your self-sovereign control centre - saved to your repository',
  'settings.tab.account': 'Account', 'settings.tab.language': 'Language', 'settings.tab.privacy': 'Privacy', 'settings.tab.notifications': 'Notifications',
  'settings.tab.accessibility': 'Accessibility', 'settings.tab.advanced': 'Advanced', 'settings.tab.challenges': 'Challenges', 'settings.tab.security': 'Security',
  'settings.tab.datarights': 'Data & Rights', 'settings.tab.atprotocol': 'AT Protocol',
  'page.compose.reply': 'Reply', 'page.compose.newPost': 'New Post', 'compose.replyingTo': 'Replying to',
  'compose.placeholder.reply': 'Write your reply...', 'compose.placeholder.post': 'What did you pull today?',
  'compose.charsLeft': 'left', 'compose.altTextLabel': 'Image description (alt text)',
  'compose.altTextPlaceholder': 'Describe the card image for screen readers...',
  'compose.whoCanReply': 'Who can reply:', 'compose.whoCanSee': 'Who can see:',
  'compose.card': 'Card', 'compose.collection': 'Collection', 'compose.post': 'Post',
  'compose.selectTradeCard': 'Select card to trade', 'compose.attachCard': 'Attach a card',
  'compose.policy.everyone': 'Everyone', 'compose.policy.followers': 'Followers', 'compose.policy.mentioned': 'Mentioned', 'compose.policy.nobody': 'No one',
  'compose.scope.public': 'Public', 'compose.scope.followers': 'Followers', 'compose.scope.mentioned': 'Mentioned', 'common.followers': 'Followers',
  'page.circles.title': 'Circles', 'page.circles.subtitle': 'Curated member groups with scoped trades', 'page.circles.new': 'New circle',
  'page.circles.yourCircles': 'Your circles', 'page.circles.discover': 'Discover', 'page.circles.empty': 'No circles yet. Create the first one.',
  'page.meetups.title': 'Meetups', 'page.meetups.subtitle': 'Vouch-gated local collector meetups', 'page.meetups.new': 'New meetup',
  'page.meetups.empty': 'No meetups scheduled. Organise the first one.',
  'page.spaces.title': 'Live Streams', 'page.spaces.subtitle': 'Collectors streaming now - tap a live ring to join', 'page.spaces.goLive': 'Go Live',
  'spaces.tab.live': 'Live Now', 'spaces.tab.recordings': 'Recordings',
  'page.messages.title': 'Messages', 'page.messages.subtitle': 'Private chats with other collectors',
  'page.messages.empty': 'No conversations yet.', 'page.messages.emptySub': "Tap Message on a collector's profile to start chatting.",
  'page.messages.select': 'Select a conversation to start chatting.',
  'page.challenges.title': 'Challenges', 'page.challenges.subtitle': 'Cooperative community goals & opt-in leaderboards',
  'challenges.tab.active': 'Active', 'challenges.tab.upcoming': 'Upcoming', 'challenges.tab.completed': 'Completed', 'challenges.tab.mine': 'My Entries',
  'page.challenges.empty': 'No challenges match. Try another tab or filter.',
  'page.achievements.title': 'Achievements', 'page.achievements.subtitle': 'Proof-based, network-verified credentials, not participation trophies',
  'page.achievements.reEvaluate': 'Re-evaluate',
  'page.packs.title': 'Pack Openings', 'page.packs.subtitle': 'Live pulls from the community',
  'page.packs.empty': 'No pack openings yet', 'page.packs.emptySub': 'Share a pull from the compose box to start a thread.',
  'page.share.title': 'Shared Content', 'page.share.subtitle': 'Received from another app',
  'page.share.empty': 'Nothing shared yet', 'page.share.emptySub': 'Share a card photo into SwapPulse from your camera or gallery to see it here.',
  'page.predictions.title': 'Predictions', 'page.predictions.subtitle': 'Community sentiment polls & market predictions',
  'predictions.tab.active': 'Active', 'predictions.tab.closed': 'Resolved', 'predictions.tab.all': 'All',
  'page.donate.title': 'Support SwapPulse', 'page.donate.subtitle': 'Keep the platform free & open-source', 'page.donate.back': 'Back to app',
  'page.help.title': 'Help & Info', 'page.help.subtitle': 'What SwapPulse does, how it works, and where to get help',
  'page.status.title': 'System Status', 'status.operational': 'Operational', 'status.degraded': 'Degraded', 'status.outage': 'Outage', 'status.maintenance': 'Maintenance',
  'page.grading.title': 'Grading Submissions', 'page.grading.subtitle': 'Track your PSA, CGC, and Beckett submissions',
  'page.whoToFollow.title': 'Who to Follow', 'page.whoToFollow.subtitle': 'Collectors recommended for you',
  'page.packParties.title': 'Pack Parties', 'page.packParties.subtitle': 'Open packs together with other collectors',
  'page.pullOfTheWeek.title': 'Pull of the Week', 'page.pullOfTheWeek.subtitle': 'Vote for the best pull this week',
  'page.tradeDashboard.title': 'Trade Dashboard', 'page.tradeDashboard.subtitle': 'Your active trades and trade history',
  'page.tradeStatusBoard.title': 'Trade Status Board', 'page.tradeStatusBoard.subtitle': 'Live trade activity across the community',
  'page.tradeThread.title': 'Negotiation', 'page.tradeThread.notFound': 'Trade not found', 'page.tradeThread.backToBoard': 'Back to Trade Board', 'page.tradeThread.board': 'Board', 'page.tradeThread.subtitle': 'Negotiate a trade',
  'page.hashtag.title': 'Hashtag', 'page.hashtag.subtitle': 'Posts tagged with this hashtag', 'hashtag.followTag': 'Follow tag',
  'page.journal.title': 'Journal', 'page.journal.loading': 'Loading journal…', 'page.journal.notFound': 'Journal not found',
  'userProfile.back': 'Back', 'userProfile.noOnSiteActivity': 'No on-site activity, this collector posts on Bluesky.',
  'userProfile.viewOnBluesky': 'View on Bluesky', 'userProfile.tradeHistoryMembers': 'Trade history is only available for SwapPulse members.',
  'userProfile.sharedCollectionsMembers': 'Shared collections are only available for SwapPulse members.',
  'userProfile.noPostsBluesky': 'No posts found on Bluesky.', 'userProfile.noPostsYet': 'No posts yet.',
  'page.terms.title': 'Terms of Service', 'page.privacy.title': 'Privacy Policy',
  'card.dataUnavailable': 'Card data unavailable', 'card.noPriceData': 'No price data', 'card.low': 'Low',
  'common.fromWeb': 'From the web', 'home.cardOfTheDay': 'Card of the Day', 'home.cardOfTheDaySub': 'Featured for notable price movement',
  'auth.guestBrowse': 'Browsing as a guest.', 'auth.guestLoginAction': 'to post, trade, and interact.', 'common.dismiss': 'Dismiss',
  'sidebar.onlineNow': 'Online now', 'sidebar.collectorsActive': 'Collectors active in the last 2 minutes.',
  'sidebar.trendingTopics': 'Trending Topics', 'sidebar.cardsLabel': 'Cards', 'sidebar.hashtagsLabel': 'Hashtags', 'sidebar.keywordsLabel': 'Keywords',
  'common.you': 'You', 'stories.yourStory': 'Your story',
  'sidebar.yourPortfolio': 'Your Portfolio', 'sidebar.activeTrades': 'Active Trades', 'sidebar.trendingCards': 'Trending Cards',
  'sidebar.offering': 'Offering', 'sidebar.wants': 'Wants', 'sidebar.cards': 'cards',
  'sidebar.mutualVouch': 'mutual vouch', 'sidebar.mutualVouches': 'mutual vouches', 'sidebar.trustScore': 'Trust',
  'sidebar.copyright': '© SwapPulse - Built on the AT Protocol · Powered by TCGdex',
  'toast.following': 'Following', 'toast.couldNotFollow': 'Could not follow',
  'profile.editProfile': 'Edit profile', 'profile.collector': 'Collector', 'profile.trustedTrader': 'Trusted Trader',
  'profile.binderEmpty': 'Your binder is empty. Add cards to your collection.', 'profile.portfolioValue': 'Portfolio value:',
  'profile.myCollectionNetwork': 'My Collection on the Network', 'profile.myTradesNetwork': 'My Trades on the Network', 'notifications.refresh': 'Refresh notifications',
  'binder.deleteConfirm': 'Delete this binder?', 'binder.notFound': 'Binder not found.', 'binder.edit': 'Edit',
  'trust.networkSubtitle': 'Vouch-based reputation across the community', 'trust.revokeConfirm': 'Revoke this vouch? It will no longer count towards their trust score.',
  'trust.relationship.tradePartner': 'Trade Partner', 'trust.relationship.repeatTrader': 'Repeat Trader', 'trust.relationship.personalAcquaintance': 'Personal', 'trust.relationship.communityMember': 'Community',
  'trust.vouchesForYou': 'Vouches for you', 'trust.noVouchesForYou': 'No one has vouched for you yet.',
  'trust.youVouchedFor': 'You vouched for', 'trust.noOutgoingVouches': "You haven't vouched for anyone yet.", 'trust.revoked': 'Revoked', 'trust.revoke': 'Revoke',
  'circles.theme.general': 'General', 'circles.theme.vintage': 'Vintage', 'circles.theme.competitive': 'Competitive', 'circles.theme.shiny': 'Shiny', 'circles.theme.investment': 'Investment', 'circles.theme.localRegion': 'Local', 'circles.theme.artist': 'Artist',
  'circles.curator': 'Curator', 'circles.member': 'Member', 'circles.members': 'members',
  'meetups.tbd': 'TBD', 'meetups.vouches': 'vouches',
  'predictions.newPoll': 'New poll', 'predictions.empty.active': 'No active polls. Create the first market prediction.', 'predictions.empty.all': 'Nothing here yet.',
  'grading.new': 'New', 'grading.empty': 'No grading submissions yet', 'grading.emptySub': "Track cards you've sent to PSA, BGS, CGC or ACE - status, tracking and grades.", 'grading.add': 'Add submission', 'grading.noTracking': 'no tracking',
  'grading.status.submitted': 'Submitted', 'grading.status.inProgress': 'In Progress', 'grading.status.graded': 'Graded', 'grading.status.returned': 'Returned', 'grading.status.rejected': 'Rejected',
  'grading.declared': 'Declared:', 'grading.expected': 'Expected:', 'grading.sent': 'Sent:', 'grading.advance': 'Advance status', 'grading.gradePlaceholder': 'Grade e.g. PSA 10',
  'achievements.evaluateError': 'Could not evaluate achievements', 'achievements.of': 'of', 'achievements.summary': 'credentials unlocked. Each is a state-dependent proof verified against your on-chain activity, revoked if the underlying proof no longer holds (after a 24h grace period).',
  'challenges.filter.all': 'All', 'challenges.filter.collective': 'Collective', 'challenges.filter.competitive': 'Competitive', 'challenges.filter.circle': 'Circle-Scoped', 'challenges.loadError': 'Failed to load',
  'spaces.all': 'All', 'spaces.sort.viewers': 'Viewers', 'spaces.sort.recent': 'Recent', 'spaces.noStreamsPlatform': 'No live streams on this platform right now.', 'spaces.noStreamsLive': 'No streams live right now', 'spaces.beFirst': 'Be the first to go live!', 'spaces.noRecordings': 'No recordings yet.',
  'share.addToCollection': 'Add to Collection', 'share.createPost': 'Create Post', 'share.dismiss': 'Dismiss',
  'tradeStatus.open': 'Open', 'tradeStatus.negotiating': 'Negotiating', 'tradeStatus.pendingShip': 'Pending Ship', 'tradeStatus.completed': 'Completed', 'tradeStatus.cancelled': 'Cancelled',
  'tradeStatus.searchPlaceholder': 'Search cards or collector…', 'tradeStatus.all': 'All', 'tradeStatus.mine': 'Mine', 'tradeStatus.noTradesFound': 'No trades found', 'tradeStatus.noTradesMine': 'You have no trades yet.', 'tradeStatus.noTradesBoard': 'No trades on the board yet.', 'tradeStatus.noTrades': 'No trades', 'tradeStatus.cards': 'Cards',
  'tradeThread.sendError': 'Could not send', 'tradeThread.markPendingShip': 'Mark Pending Ship', 'tradeThread.markCompleted': 'Mark Completed', 'tradeThread.statusError': 'Could not update status', 'tradeThread.watchError': 'Could not update watch status', 'tradeThread.watching': 'Watching', 'tradeThread.watchTrade': 'Watch this trade', 'tradeThread.watchSub': 'Get notified on updates and completion.', 'tradeThread.disputeFiled': 'Dispute filed', 'tradeThread.reportDispute': 'Report a Dispute', 'tradeThread.disputeSub': 'Flag for moderation if something went wrong with the cards.', 'tradeThread.status': 'Status', 'tradeThread.cancelTrade': 'Cancel trade', 'tradeThread.startConversation': 'Start the conversation - ask about condition, shipping, or terms.', 'tradeThread.messagePlaceholder': 'Message…',
  'tradeDashboard.active': 'Active', 'tradeDashboard.pendingShip': 'Pending Ship', 'tradeDashboard.completed': 'Completed', 'tradeDashboard.cancelled': 'Cancelled', 'tradeDashboard.signIn': 'Sign in to view your dashboard', 'tradeDashboard.goToLogin': 'Go to login', 'tradeDashboard.myActiveTrades': 'My Active Trades', 'tradeDashboard.noActive': 'No active trades.', 'tradeDashboard.browseBoard': 'Browse the board', 'tradeDashboard.toStartOne': 'to start one.', 'tradeDashboard.watching': 'Watching', 'tradeDashboard.notWatching': 'Not watching any trades. Open a trade and tap the bell to get notified.',
  'binder.editTitle': 'Edit Binder', 'binder.newTitle': 'New Binder', 'binder.editSubtitle': 'Arrange your prized cards into pages', 'binder.save': 'Save', 'binder.saveError': 'Failed to save binder', 'binder.titlePlaceholder': "Binder title (e.g. 'My Holos')", 'binder.descPlaceholder': 'Short description...', 'binder.theme': 'Theme', 'binder.visibility': 'Visibility', 'binder.visibilityPublic': 'Public', 'binder.visibilityFollowers': 'Followers', 'binder.visibilityPrivate': 'Private', 'binder.coverPlaceholder': 'Cover image URL (optional)', 'binder.page': 'Page', 'binder.captionPlaceholder': 'caption', 'binder.addPage': 'Add page',
  'admin.title': 'Admin', 'admin.subtitle': 'Production readiness dashboard', 'admin.adminsOnly': 'Admins only', 'admin.noAccess': "You don't have access to this page.", 'admin.loadError': 'Failed to load metrics',
  'moderation.staffOnly': 'Staff only', 'moderation.staffOnlySub': 'The moderator dashboard is restricted to staff and administrators.', 'moderation.title': 'Moderator Dashboard', 'moderation.subtitle': 'Review flagged posts and apply moderation decisions', 'moderation.refresh': 'Refresh', 'moderation.tab.posts': 'Flagged Posts', 'moderation.tab.disputes': 'Trade Disputes', 'moderation.tab.enforcement': 'Account Enforcement', 'moderation.tab.bots': 'Bot Protection', 'moderation.hideFilters': 'Hide Filters', 'moderation.showFilters': 'Show Filters',
  // About page
  'about.title': 'About SwapPulse', 'about.back': 'Back to SwapPulse', 'about.missionTitle': 'Our Mission',
  'about.missionBody': 'SwapPulse exists to give Pokémon TCG collectors a home that belongs to them — not to a corporation, an algorithm, or an ad network. We believe a hobby built on community, trust, and trade should be powered by software that respects all three. Every feature is free, every record is portable, and every decision is made in the open.',
  'about.whatTitle': 'What is SwapPulse?',
  'about.whatBody1': 'SwapPulse is a decentralized social network and collection manager for Pokémon TCG collectors. It combines collection tracking, peer-to-peer trading, social feeds, AI tools, and community features into a single platform built on the AT Protocol — the same open standard that powers Bluesky. That means your posts, trades, and identity are federated and portable; you are never locked in.',
  'about.whatBody2': 'Card data is sourced from TCGDex, an open Pokémon TCG catalogue, and is available in nine languages. The platform is funded entirely by voluntary donations — there are no paid features, no premium tiers, and no advertising.',
  'about.feature.collection': 'Track your collection, portfolio value, and set completion', 'about.feature.trading': 'Trade cards peer-to-peer with threaded negotiations and trade chains', 'about.feature.scanner': 'Scan cards with AI and get instant TCGDex catalogue matches', 'about.feature.social': 'Post pulls, write journals, build digital binders, and review cards', 'about.feature.community': 'Join circles, meetups, challenges, and pack parties', 'about.feature.market': 'Watch the market with price tracking and alerts', 'about.feature.voice': 'Host voice spaces and publish podcasts', 'about.feature.achievements': 'Earn proof-based achievements verified against your on-chain activity',
  'about.principlesTitle': 'Core Principles', 'about.principle.free.title': 'Free & Open-Source', 'about.principle.free.body': 'No paywalls, no premium tiers, no ads. SwapPulse is funded entirely by voluntary donations and licensed under AGPL-3.0 so the community can self-host and audit every line.', 'about.principle.decentralized.title': 'Decentralized by Design', 'about.principle.decentralized.body': 'Built on the AT Protocol, your identity, posts, and collection are portable. You own your data — export it, migrate PDS, or use it in any compatible app at any time.', 'about.principle.community.title': 'Community-Moderated', 'about.principle.community.body': 'Trust is earned through vouches, not handed down. Moderation blends AI screening with human review, and reputation is built by the collectors who trade with you.', 'about.principle.privacy.title': 'Privacy-First', 'about.principle.privacy.body': 'Direct messages are end-to-end encrypted with no backdoor. Your private key lives in your browser. We collect the minimum needed to run the platform and nothing more.',
  'about.openSource': 'Open-source under AGPL-3.0', 'about.builtOn': 'Built on the AT Protocol · Powered by TCGDex', 'about.joinTitle': 'Join the community', 'about.joinBody': 'Create a free account, explore the catalogue, or start trading today.', 'about.callToAction.createAccount': 'Create account', 'about.callToAction.exploreCards': 'Explore cards', 'about.callToAction.supportUs': 'Support us', 'about.seoTitle': 'About', 'about.seoDescription': 'SwapPulse is a free, open-source, decentralized social network for Pokémon TCG collectors — built on the AT Protocol, powered by TCGDex.',
  // Collection page
  'collection.all': 'All', 'collection.binderFull': 'Your binder is full ({gridSize} grid). Remove a card to add another.',
  'collection.cardsMarkedAs': '{count} cards marked as {condition}', 'collection.checklistManager': 'Checklist Manager',
  'collection.completionDesc': 'Track set completion and download printable checklists.', 'collection.conditionUpdated': 'Condition updated',
  'collection.doneSelecting': 'Done', 'collection.empty': 'Your collection is empty',
  'collection.emptySub': 'Add cards from the catalogue or import a CSV to start tracking.', 'collection.exploreCards': 'Explore cards',
  'collection.grid': 'Grid', 'collection.importCsv': 'Import CSV', 'collection.selectCards': 'Select', 'collection.updateFailed': 'Update failed',
  'collection.sortRecent': 'Recent', 'collection.sortRarest': 'Rarest first', 'collection.sortCommon': 'Common first',
  // Explore page
  'explore.addedToWishlist': 'Added to wishlist', 'explore.addToWishlist': 'Add to wishlist', 'explore.allSelected': 'All selected',
  'explore.cardsCount': 'cards', 'explore.cardsSaved': '{count} cards saved to your wishlist', 'explore.couldNotAdd': 'Could not add',
  'explore.done': 'Done', 'explore.everybodyFeed': 'Everybody Feed', 'explore.fromNetwork': 'From the Network',
  'explore.latestPosts': 'Latest Posts', 'explore.noCardsFound': 'No cards found for "{query}"', 'explore.noPosts': 'No posts yet',
  'explore.recentSets': 'Recent Sets', 'explore.results': 'results', 'explore.searchFailed': 'Search failed',
  'explore.searchFailedDesc': 'Could not search cards. Please try again.', 'explore.searchPlaceholder': 'Search cards…',
  'explore.select': 'Select', 'explore.selectAll': 'Select all', 'explore.selected': 'selected',
  'explore.rarityAll': 'All rarities', 'explore.rarityCommon': 'Common', 'explore.rarityUncommon': 'Uncommon',
  'explore.rarityRare': 'Rare', 'explore.rarityHolo': 'Holo', 'explore.rarityEx': 'EX / V', 'explore.raritySecret': 'Secret / Rainbow',
  'explore.allSets': 'All sets', 'explore.searchSets': 'Search sets…', 'explore.noSets': 'No sets found.',
  'explore.filters': 'Filters', 'explore.filterCards': 'Filter cards', 'explore.closeFilters': 'Close filters',
  'explore.type': 'Type', 'explore.allTypes': 'All types', 'explore.priceRange': 'Price range ($)',
  'explore.min': 'Min', 'explore.minPrice': 'Minimum price', 'explore.max': 'Max', 'explore.maxPrice': 'Maximum price',
  'explore.clear': 'Clear', 'explore.apply': 'Apply',
  'page.packParties.newParty': 'New Party', 'page.packParties.empty': 'No pack parties yet',
  'page.packParties.emptySub': 'Schedule a synchronized pack opening and invite collectors to join the fun.',
  'page.packParties.schedule': 'Schedule a Party', 'page.packParties.live': 'LIVE', 'page.packParties.completed': 'Completed',
  'page.packParties.joinNow': 'Join Now', 'page.packParties.createTitle': 'Schedule a Pack Party',
  'page.packParties.createSub': 'Pick a set, set a time, and invite collectors to open packs together.',
  'page.packParties.titleLabel': 'Title', 'page.packParties.descLabel': 'Description (optional)',
  'page.packParties.setLabel': 'Set (optional)', 'page.packParties.whenLabel': 'When',
  'page.packParties.maxParticipants': 'Max participants', 'page.packParties.scheduleBtn': 'Schedule',
  'page.packParties.createError': 'Could not create party',
  'page.pullOfTheWeek.nominate': 'Nominate', 'page.pullOfTheWeek.leading': 'Leading with {count} votes',
  'page.pullOfTheWeek.empty': 'No nominations yet', 'page.pullOfTheWeek.emptySub': 'Be the first to nominate your best pull this week!',
  'page.pullOfTheWeek.nominatePull': 'Nominate a Pull', 'page.pullOfTheWeek.voted': 'Voted',
  'page.pullOfTheWeek.alreadyVoted': 'Already voted', 'page.pullOfTheWeek.vote': 'Vote',
  'page.pullOfTheWeek.nominateTitle': 'Nominate Your Pull', 'page.pullOfTheWeek.nominateSub': 'Enter the card you pulled this week.',
  'page.pullOfTheWeek.cardName': 'Card name', 'page.pullOfTheWeek.cardId': 'Card ID (optional)',
  'page.pullOfTheWeek.imageUrl': 'Image URL (optional)', 'page.pullOfTheWeek.rarity': 'Rarity', 'page.pullOfTheWeek.set': 'Set',
  'page.pullOfTheWeek.voteError': 'Could not vote', 'page.pullOfTheWeek.nominateError': 'Could not nominate',
  'challenge.ended': 'Ended', 'challenge.timeLeftDays': '{d}d {h}h left', 'challenge.timeLeftHours': '{h}h {m}m left',
  'challenge.timeLeftMinutes': '{m}m left', 'challenge.collectiveGoal': 'Collective community goal',
  'challenge.competitiveChallenge': 'Competitive leaderboard challenge', 'challenge.all': 'All',
  'challenge.circle': 'Circle', 'challenge.global': 'Global', 'challenge.communityProgress': 'Community progress',
  'challenge.contributors': 'Contributors', 'challenge.contributions': 'Contributions', 'challenge.complete': 'Complete',
  'challenge.youContributed': "You've contributed", 'challenge.items': 'items',
  'challenge.leaderboardPreview': 'Leaderboard preview', 'challenge.viewFull': 'View full →',
  'challenge.noParticipants': 'No opt-in participants yet.', 'challenge.rules': 'Rules', 'challenge.goal': 'Goal',
  'challenge.filters': 'Filters', 'challenge.reward': 'Reward', 'challenge.allContributors': '(all contributors)',
  'challenge.topRankers': '(top rankers)', 'challenge.yourContributions': 'Your recent contributions',
  'challenge.counted': 'counted', 'challenge.notFound': 'Not found', 'challenge.optInCount': '{count} opt-in',
  'challenge.totalCount': '{count} total', 'challenge.youLabel': 'You', 'challenge.contributed': '{count} contributed',
  'challenge.notRanked': 'not ranked',
  'circle.theme.general': 'General', 'circle.theme.vintage': 'Vintage', 'circle.theme.competitive': 'Competitive',
  'circle.theme.shiny': 'Shiny', 'circle.theme.investment': 'Investment', 'circle.theme.localRegion': 'Local Region',
  'circle.theme.artist': 'Artist', 'circle.notFound': 'Circle not found.', 'circle.curator': 'Curator',
  'circle.curatorLower': 'curator', 'circle.leave': 'Leave', 'circle.private': 'Private', 'circle.join': 'Join',
  'circle.memberSingular': 'member', 'circle.memberPlural': 'members', 'circle.leftCircle': 'You have left this circle.',
  'circle.privateDesc': 'This is a private circle. Only members can view its contents.', 'circle.membersTitle': 'Members',
  'circle.member': 'Member', 'circle.noProfiles': 'No member profiles.', 'circle.scopedTrades': 'Circle-scoped trades',
  'circle.noScopedTrades': 'No circle-scoped trades yet.', 'circle.offering': 'Offering', 'circle.wants': 'Wants',
  'circle.negotiate': 'Negotiate', 'circle.joinToSee': 'Join this circle to see member-only trades.',
  'meetup.new': 'New Meetup', 'meetup.titleLabel': 'Title', 'meetup.descLabel': 'Description',
  'meetup.dateTime': 'Date & time', 'meetup.duration': 'Duration (min)', 'meetup.venue': 'Venue / location',
  'meetup.region': 'Region', 'meetup.capacity': 'Capacity', 'meetup.requiredVouches': 'Required vouches',
  'meetup.requiredVouchesHint': 'Min incoming vouches to view attendees.', 'meetup.create': 'Create meetup',
  'meetup.errorRequired': 'Title, description, date/time and location are required', 'meetup.errorFailed': 'Failed to create meetup',
  'circle.create.new': 'New Circle', 'circle.create.name': 'Name', 'circle.create.description': 'Description',
  'circle.create.theme': 'Theme', 'circle.create.visibility': 'Visibility', 'circle.create.region': 'Region',
  'circle.create.nameRequired': 'Name required', 'circle.create.failed': 'Failed to create circle', 'circle.create.createBtn': 'Create circle',
  'circle.vis.private': 'Private', 'circle.vis.membersVisible': 'Members visible', 'circle.vis.public': 'Public',
  'poll.new': 'New Market Poll', 'poll.card': 'Card', 'poll.searchCards': 'Search cards', 'poll.change': 'Change',
  'poll.currentAvg': 'Current {source} avg: {price}', 'poll.priceNotTracked': 'Price not tracked - outcome will be inconclusive',
  'poll.yourPrediction': 'Your prediction', 'poll.bullish': 'Bullish', 'poll.bearish': 'Bearish', 'poll.neutral': 'Neutral',
  'poll.closesIn': 'Closes in', 'poll.1day': '1 day', 'poll.7days': '7 days', 'poll.30days': '30 days',
  'poll.priceSource': 'Price source', 'poll.question': 'Question', 'poll.createBtn': 'Create poll',
  'poll.pickCard': 'Pick a card first', 'poll.writeQuestion': 'Write a question', 'poll.failed': 'Failed to create poll',
  'poll.pickCardTitle': 'Pick a card to poll', 'poll.questionPlaceholder': 'Will this card rise in the next 7 days?',
  'poll.dirRise': 'rise above', 'poll.dirFall': 'fall below', 'poll.dirStay': 'stay around',
  'poll.questionTemplate': 'Will {card} {direction} its current price in the next {days} days?',
  'grading.new': 'New grading submission', 'grading.cardFromCollection': 'Card from your collection',
  'grading.selectCard': 'Select a card…', 'grading.gradingService': 'Grading service',
  'grading.trackingNumber': 'Tracking number', 'grading.declaredValue': 'Declared value (£)',
  'grading.expectedReturn': 'Expected return date', 'grading.submit': 'Submit',
  'grading.pickCard': 'Pick a card from your collection', 'grading.couldNotSave': 'Could not save',
  'auth.login.welcomeBack': 'Welcome back', 'auth.login.subtitle': 'Sign in with your email, no password needed',
  'auth.login.noAccount': "Don't have an account?", 'auth.login.createOne': 'Create one',
  'auth.login.codeExpired': 'Code expired. Please request a new one.', 'auth.login.enterEmail': 'Enter your email.',
  'auth.login.codeSent': 'We sent a 6-digit code to {email}. It expires in 5 minutes.',
  'auth.login.couldNotSend': 'Could not send login code', 'auth.login.enterCode': 'Enter the 6-digit code.',
  'auth.login.verificationFailed': 'Verification failed. Please try again.', 'auth.login.invalidCode': 'Invalid or expired code',
  'auth.login.loginFailed': 'Login failed. Please try again.', 'auth.login.email': 'Email',
  'auth.login.stayLoggedIn': 'Stay logged in on this device', 'auth.login.sendingCode': 'Sending code...',
  'auth.login.sendCode': 'Send login code', 'auth.login.enterCodeSent': 'Enter the code sent to {email}',
  'auth.login.codeExpiresIn': 'Code expires in {time}', 'auth.login.verifying': 'Verifying...',
  'auth.login.verifyLogin': 'Verify & log in', 'auth.login.changeEmail': 'Change email', 'auth.login.resendCode': 'Resend code',
  'auth.login.setupLinkSent': "We've sent a sign-in link to {email}. Click the link in the email to sign in instantly, next time you'll get a 6-digit code instead.",
  'auth.login.backToLogin': 'Back to login', 'auth.login.accountSuspended': 'Account suspended',
  'auth.login.suspensionLifted': 'Your suspension will be lifted on {date}.',
  'auth.login.suspensionIndefinite': 'This suspension is indefinite. If you believe this is an error, please contact support.',
  'auth.login.notFoundTitle': 'No account found with this email address.',
  'auth.login.notFoundDesc': "You'll need to create an account to join SwapPulse and start collecting, trading, and connecting.",
  'auth.login.createAccount': 'Create an account',
  'auth.register.createAccount': 'Create your account', 'auth.register.subtitle': 'Sign up, no password needed, just your email',
  'auth.register.haveAccount': 'Already have an account?', 'auth.register.login': 'Log in', 'auth.register.email': 'Email',
  'auth.register.ageConfirm': 'I confirm I am 13 or older (under-16s need a parent or guardian\'s consent).',
  'auth.register.termsConfirm': "I have read and agree to SwapPulse's", 'auth.register.terms': 'Terms',
  'auth.register.privacyConfirm': "I have read and agree to SwapPulse's", 'auth.register.privacyPolicy': 'Privacy Policy',
  'auth.register.continue': 'Continue', 'auth.register.creating': 'Creating account...',
  'auth.register.ageError': 'Please confirm you are 13 or older to create an account.',
  'auth.register.termsError': 'Please agree to the Terms to create an account.',
  'auth.register.privacyError': 'Please agree to the Privacy Policy to create an account.',
  'auth.register.confirmTitle': 'Confirm your email',
  'auth.register.confirmSubtitle': "Re-enter your email address to make sure it's correct, this is where we'll send your verification code",
  'auth.register.backToEdit': 'Back to edit', 'auth.register.youEntered': 'You entered', 'auth.register.confirmEmail': 'Confirm email',
  'auth.register.sendVerification': 'Send verification code', 'auth.register.sendingCode': 'Sending code...',
  'auth.register.emailMismatch': 'Email addresses do not match. Please check and try again.',
  'auth.register.emailUnavailable': 'This email address is not available.', 'auth.register.registrationFailed': 'Registration failed',
  'auth.register.verifyTitle': 'Verify your email', 'auth.register.verifySubtitle': 'We sent a code to {email}',
  'auth.register.backToLogin': 'Back to log in', 'auth.register.verify': 'Verify', 'auth.register.verifying': 'Verifying...',
  'auth.register.didntReceive': "Didn't receive the code?", 'auth.register.resend': 'Resend',
  'auth.register.enterCode': 'Enter the 6-digit code.', 'auth.register.invalidCode': 'Invalid verification code',
  'auth.register.resendFailed': 'Failed to resend code',
  'auth.forgot.migrateTitle': 'Migrate your account', 'auth.forgot.resetTitle': 'Reset password',
  'auth.forgot.migrateSubtitle': 'Set a password to move off Google sign-in', 'auth.forgot.resetSubtitle': "We'll send you a link to reset it",
  'auth.forgot.backToLogin': 'Back to log in',
  'auth.forgot.migrateSent': "If an account exists with that email, you'll receive a link to set your new password and complete migration.",
  'auth.forgot.resetSent': "If an account exists with that email, you'll receive a password reset link shortly.",
  'auth.forgot.email': 'Email address', 'auth.forgot.sending': 'Sending...', 'auth.forgot.sendReset': 'Send reset link',
  'auth.reset.signingIn': 'Signing you in', 'auth.reset.confirmingLink': 'Confirming your sign-in link',
  'auth.reset.signedIn': "You're signed in! Next time, you'll get a 6-digit code instead.", 'auth.reset.goHome': 'Go to home',
  'auth.reset.completeSignin': 'Complete your sign-in', 'auth.reset.enterEmailContinue': 'Enter your email to continue',
  'auth.reset.email': 'Email', 'auth.reset.continue': 'Continue', 'auth.reset.enterEmailError': 'Enter your email to continue.',
  'auth.reset.couldNotSetup': 'Could not set up passwordless login.', 'auth.reset.couldNotSetupRetry': 'Could not set up passwordless login. Please try again.',
  'auth.reset.invalidLink': 'Invalid reset link', 'auth.reset.invalidSubtitle': 'This password reset link is missing or invalid',
  'auth.reset.requestNew': 'Request a new link',
  'auth.reset.invalidDesc': 'The link you used appears to be incomplete. Please request a new password reset email.',
  'auth.reset.migrateTitle': 'Set your new password', 'auth.reset.newTitle': 'New password',
  'auth.reset.migrateSubtitle': 'Complete your migration from Google', 'auth.reset.newSubtitle': 'Enter your new password below',
  'auth.reset.newPassword': 'New Password', 'auth.reset.confirmPassword': 'Confirm Password',
  'auth.reset.minChars': 'At least 12 characters',
  'auth.reset.passwordHint': 'Minimum 12 characters - use a mix of upper and lower case, numbers and symbols.',
  'auth.reset.passwordsDontMatch': 'Passwords do not match', 'auth.reset.resetting': 'Resetting...', 'auth.reset.resetPassword': 'Reset password',
  'auth.reset.failedReset': 'Failed to reset password',
  'auth.activate.title': 'Activate your account', 'auth.activate.subtitle': 'Enter the code from your email to activate',
  'auth.activate.backToLogin': 'Back to log in',
  'auth.activate.linkValid': 'Your activation link is valid. Enter the code from your email to activate.',
  'auth.activate.linkExpired': 'This activation link has expired. Resend a fresh link, then enter the new code.',
  'auth.activate.linkInvalid': 'This activation link is not valid. You can still activate by entering your email and the code from your verification email.',
  'auth.activate.enterEmailResend': 'Enter your email to resend the activation link.',
  'auth.activate.activationSent': 'Activation email sent. Check your inbox for the code and link.', 'auth.activate.failedResend': 'Failed to resend',
  'auth.activate.enterEmailError': 'Enter your email.', 'auth.activate.enterCode': 'Enter the 6-digit code.',
  'auth.activate.invalidCode': 'Invalid verification code', 'auth.activate.email': 'Email', 'auth.activate.verificationCode': 'Verification code',
  'auth.activate.activating': 'Activating...', 'auth.activate.activateAccount': 'Activate account', 'auth.activate.resendActivation': 'Resend activation email',
  'common.skipToContent': 'Skip to content',
  'page.accountDeleted.title': 'Your account has been permanently deleted',
  'page.accountDeleted.desc1': 'All data linked to your account, your collection, trades, posts, binders, reputation, and federated records, has been irrevocably erased.',
  'page.accountDeleted.desc2': 'Your username has been released and your email address can be used to register again in the future, should you choose to return to SwapPulse.',
  'page.accountDeleted.backHome': 'Back to home',
  'page.orderComplete.title': 'Order complete', 'page.orderComplete.desc': 'Thanks for your purchase. The seller will be notified and your order is now being processed.',
  'page.orderComplete.back': 'Back to SwapPulse',
  'page.donate.backToApp': 'Back to app', 'page.donateThanks.title': 'Thank you for supporting SwapPulse!',
  'page.donateThanks.desc': "Your generosity keeps the platform free and open-source for every collector. We've emailed you a receipt.",
  'page.donateThanks.backToApp': 'Back to the app',
  'page.fiatSuccess.desc': "Your card donation has been processed. We've emailed you a receipt.",
  'page.invite.title': "You're invited to SwapPulse",
  'page.invite.subtitle': 'The decentralized social network for Pokémon TCG collectors. Track your collection, trade cards, and connect with a community that shares your passion, all built on the AT Protocol.',
  'page.invite.verifying': 'Verifying your invite code…', 'page.invite.createAccount': 'Create your free account',
  'page.invite.noPassword': 'No password needed, just your email. Takes less than a minute.',
  'page.invite.invalidTitle': "This invite link isn't valid",
  'page.invite.invalidDesc': 'The code may have already been used or expired. You can still explore SwapPulse without an account.',
  'page.invite.explore': 'Explore SwapPulse',
  'page.invite.feature.scanner.title': 'AI Card Scanner', 'page.invite.feature.scanner.desc': 'Scan cards to instantly identify and add them to your collection.',
  'page.invite.feature.trust.title': 'Trade with Trust', 'page.invite.feature.trust.desc': 'Trade safely with verified collectors backed by a vouch-based trust graph.',
  'page.invite.feature.binders.title': 'Digital Binders', 'page.invite.feature.binders.desc': 'Showcase your best pulls in beautiful, customizable digital binders.',
  'page.invite.feature.circles.title': 'Community Circles', 'page.invite.feature.circles.desc': 'Join circles, meetups, and challenges with collectors who share your interests.',
  'page.invite.feature.data.title': 'Your Data, Yours', 'page.invite.feature.data.desc': 'Built on the AT Protocol, your posts federate to Bluesky and beyond.',
  'page.invite.feature.free.title': 'Free & Open Source', 'page.invite.feature.free.desc': 'No paywalls, no ads, no tracking. Funded by voluntary donations.',
  'page.invite.migrateTitle': 'Already on Bluesky? Migrate your account',
  'page.invite.migrateDesc': 'If you already have a Bluesky account, you can link it to SwapPulse after creating your account. This lets you use the same identity, brings over your follows, and attributes your posts to you across the federated network.',
  'page.invite.step1.title': 'Create your SwapPulse account', 'page.invite.step1.desc': 'Use the button above to register with your email. It only takes a minute.',
  'page.invite.step2.title': 'Go to Settings → AT Protocol', 'page.invite.step2.desc': 'After logging in, open Settings and find the "Link Your Bluesky Account" section.',
  'page.invite.step3.title': 'Enter your Bluesky app password', 'page.invite.step3.desc': 'Use a Bluesky app password (not your main password) from bsky.app/settings/app-passwords. Enter your Bluesky handle and the app password to link.',
  'page.invite.step4.title': 'Your follows migrate automatically', 'page.invite.step4.desc': 'Once linked, your existing Bluesky follows are imported into SwapPulse so your feed is populated from day one.',
  'page.invite.step5.title': 'Post as yourself', 'page.invite.step5.desc': 'Your posts, replies, likes, and follows now federate from your own Bluesky identity, not the shared bridge account.',
  'page.invite.migrateNote': 'Your Bluesky account stays fully intact, linking just lets SwapPulse read and write to it on your behalf. You can unlink at any time from Settings.',
  'page.invite.getStarted': 'Get started',
  'page.invite.footer': '© SwapPulse, Built on the AT Protocol · Powered by TCGdex · Free & Open Source',
  'page.leaderboard.title': 'Leaderboard', 'page.leaderboard.challenge': 'Challenge',
  'page.leaderboard.empty': 'No one has opted into this leaderboard yet. Be the first?',
  'page.leaderboard.rank': 'Rank', 'page.leaderboard.collector': 'Collector', 'page.leaderboard.score': 'Score',
  'page.leaderboard.entries': 'Entries', 'page.leaderboard.verified': 'Verified',
  'page.leaderboard.stats': '{visible} visible · {total} total participants',
  'page.leaderboard.privacyNote': 'Some collectors have chosen not to appear. Respect their choice.',
  'meetup.attending.yes': 'Going', 'meetup.attending.maybe': 'Maybe', 'meetup.attending.no': "Can't make it",
  'meetup.notFound': 'Meetup not found.', 'meetup.cancelConfirm': 'Cancel this meetup?', 'meetup.tbd': 'TBD',
  'meetup.stats': '{going} going · {maybe} maybe · {cap} cap', 'meetup.cancelled': 'This meetup has been cancelled.',
  'meetup.organisedBy': 'Organised by {name}', 'meetup.yourRsvp': 'Your RSVP', 'meetup.bringingBinder': 'Bringing my trade binder',
  'meetup.lookingFor': 'Looking for (comma separated)', 'meetup.updateRsvp': 'Update RSVP', 'meetup.sendRsvp': 'Send RSVP',
  'meetup.attendees': 'Attendees', 'meetup.vouchesNeeded': '{needed} vouches needed · you have {yours}',
  'meetup.noRsvps': 'No RSVPs yet. Be the first!', 'meetup.attendee': 'Attendee', 'meetup.binder': 'Binder',
  'meetup.vouchGated': 'Attendee list is vouch-gated. You need {needed} incoming vouches (you have {yours}) to see who\'s coming.',
  'page.incident.title': 'Incident Details', 'page.incident.loadError': 'Failed to load incident',
  'page.incident.affectedServices': 'Affected Services', 'page.incident.timeline': 'Incident Timeline',
  'page.incident.noUpdates': 'No updates have been posted yet.', 'page.incident.by': 'by {author}',
  'page.incident.backToStatus': 'Back to status page', 'page.incident.started': 'Started', 'page.incident.resolved': 'Resolved',
  'page.space.notFound': 'Space not found',
  'banner.activation.desc': "Your account isn't activated yet. Activate it to secure your access - unactivated accounts are deleted after 90 days.",
  'banner.activation.enterCode': 'Enter code', 'banner.activation.sent': 'Activation email sent',
  'banner.activation.sentDesc': 'Check your inbox for the code and link.', 'banner.activation.couldNotResend': 'Could not resend',
  'common.sending': 'Sending...',
  'banner.alpha.title': 'SwapPulse is in alpha.', 'banner.alpha.desc': 'Features may change or be removed as we build and improve the site.',
  'banner.alpha.learnMore': 'Learn more',
  'report.title': 'Report content', 'report.desc': 'Help us keep SwapPulse safe. Reports are reviewed by our moderation team and help our AI agent learn.',
  'report.why': 'Why are you reporting this?', 'report.details': 'Additional details (optional)',
  'report.detailsPlaceholder': "Tell us more about what's wrong…", 'report.submit': 'Submit report',
  'toast.reportSubmitted': 'Report submitted', 'toast.reportSubmittedDesc': 'Thank you, our moderation team will review it.',
  'toast.reportFailed': 'Could not submit report',
  'report.reason.spam.label': 'Spam', 'report.reason.spam.desc': 'Repeated low-effort or flooding',
  'report.reason.scam.label': 'Scam / Fraud', 'report.reason.scam.desc': 'Soliciting money, phishing, fake giveaways',
  'report.reason.harassment.label': 'Harassment', 'report.reason.harassment.desc': 'Personal attacks or bullying',
  'report.reason.nsfw.label': 'NSFW', 'report.reason.nsfw.desc': 'Sexual or graphic content',
  'report.reason.off_topic.label': 'Off-topic', 'report.reason.off_topic.desc': 'Derailing discussions',
  'report.reason.misgraded.label': 'Misgraded card', 'report.reason.misgraded.desc': 'Deliberate condition misrepresentation',
  'report.reason.impersonation.label': 'Impersonation', 'report.reason.impersonation.desc': 'Pretending to be someone else',
  'report.reason.other.label': 'Other', 'report.reason.other.desc': 'Something else',
  'externalLink.title': 'Leaving SwapPulse', 'externalLink.desc': "You're about to open an external link. It will open in a new tab.",
  'externalLink.continue': 'Continue',
  'cookie.title': 'Cookie preferences', 'cookie.desc': 'We use essential cookies to run SwapPulse. Optional cookies help us improve. See our',
  'cookie.acceptAll': 'Accept all', 'cookie.rejectAll': 'Reject all', 'cookie.hideOptions': 'Hide options',
  'cookie.preferences': 'Preferences', 'cookie.savePrefs': 'Save preferences',
  'cookie.cat.essential.label': 'Essential', 'cookie.cat.essential.desc': 'Login, session, security. Always on.',
  'cookie.cat.functional.label': 'Functional', 'cookie.cat.functional.desc': 'Preferences, offline cache, PWA features.',
  'cookie.cat.analytics.label': 'Analytics', 'cookie.cat.analytics.desc': 'Aggregate usage insights (no individual tracking).',
  'cookie.cat.marketing.label': 'Marketing', 'cookie.cat.marketing.desc': 'Onboarding emails and weekly digest.',
  'feedback.label': 'Feedback', 'feedback.title': 'Send feedback', 'feedback.kind': 'What kind of feedback?',
  'feedback.titleLabel': 'Title', 'common.optional': '(optional)', 'feedback.titlePlaceholder': 'Summarise your feedback in a few words',
  'feedback.rating': 'Rate your experience', 'feedback.comments': 'Comments', 'feedback.snapshot': 'Page snapshot',
  'feedback.capturing': 'Capturing page…', 'feedback.snapshotUnavailable': 'Snapshot unavailable - your comments still help.',
  'feedback.send': 'Send feedback', 'feedback.sendAria': 'Send feedback',
  'toast.addComment': 'Add a comment', 'toast.addCommentDesc': 'Tell us what you noticed.',
  'toast.feedbackSent': 'Feedback sent', 'toast.feedbackSentDesc': 'Thanks - our team will review it.',
  'toast.feedbackFailed': 'Could not send feedback', 'toast.tryAgain': 'Please try again later.',
  'feedback.commentsPlaceholder': "Tell us more about your experience, what you'd like to see, or what went wrong…",
  'feedback.cat.suggestion.label': 'Suggestion', 'feedback.cat.suggestion.desc': 'A new feature idea',
  'feedback.cat.bug.label': 'Bug Report', 'feedback.cat.bug.desc': 'Something is broken',
  'feedback.cat.comment.label': 'Comment', 'feedback.cat.comment.desc': 'General thoughts',
  // Footer
  'footer.about': 'About',
  // Help page
  'help.about': 'About SwapPulse', 'help.aboutText': 'SwapPulse is a decentralized social network and collection manager for Pokémon TCG collectors, built on the AT Protocol and powered by TCGDex. Every feature is free, your data is portable, and the community moderates itself.',
  'help.alpha': 'Alpha Software', 'help.alphaDesc': 'SwapPulse is actively being built. Features may change, move, or be removed as we learn what collectors want.',
  'help.donate': 'Donate', 'help.faq': 'FAQ', 'help.feedbackDesc': 'Use the Feedback button on the right edge of the screen to send a snapshot of the page and your comment to the team.',
  'help.guides': 'Guides', 'help.helpCentre': 'Help Centre', 'help.lexiconDesc': 'SwapPulse uses {n} custom AT Protocol lexicon types for its records.',
  'help.lexiconRef': 'Lexicon Reference', 'help.noResults': 'No results for "{query}"', 'help.noResultsDesc': 'Try a different search term or browse the guides above.',
  'help.searchPlaceholder': 'Search help…', 'help.sendFeedback': 'Send Feedback', 'help.support': 'Support SwapPulse',
  'help.supportDesc': 'SwapPulse is free and open-source, funded entirely by voluntary donations.', 'help.systemStatus': 'System Status',
  'help.systemStatusDesc': 'Check if a service is down or undergoing maintenance.', 'help.troubleshooting': 'Troubleshooting',
  'help.category.collection': 'Collection & Catalogue', 'help.category.trading': 'Trading', 'help.category.social': 'Social & Community',
  'help.category.voice': 'Voice & Podcasts', 'help.category.challenges': 'Challenges & Achievements', 'help.category.aiAssistants': 'AI Assistants',
  'help.category.account': 'Account & Settings', 'help.category.platform': 'Platform',
  // Journal detail
  'journal.anonymousAuthor': 'Anonymous Collector', 'journal.backToExplore': 'Back to Explore', 'journal.backToProfile': 'Back to profile',
  'journal.likes': 'likes', 'journal.stats.cards': 'cards', 'journal.stats.set': 'set completion', 'journal.stats.value': 'value',
  // Market watch
  'market.cardsSynced': '{count} cards synced', 'market.cardsTracked': '{count} cards tracked', 'market.noPrices': 'No price data yet. Tap sync to fetch latest prices.',
  'market.priceAlerts': 'Price Alerts', 'market.topGainers': 'Top Gainers', 'market.topLosers': 'Top Losers',
  'market.trackedPrices': 'Tracked Prices', 'market.viewCollection': 'View Collection', 'market.yourPortfolio': 'Your Portfolio',
  // Post detail
  'post.backHome': 'Back to home', 'post.limited': 'This post has limited visibility', 'post.limitedSub': 'Only {audience} can see this post.',
  'post.loading': 'Loading post…', 'post.notFound': 'Post not found', 'post.replies': 'Replies', 'post.title': 'Post',
  // Profile
  'profile.tab.collections': 'Collections',
  // Settings
  'settings.tab.apppasswords': 'App Passwords',
  // Share dialog
  'share.title': 'Share', 'share.editMessage': 'Edit Message', 'share.copyLink': 'Copy Link', 'share.copied': 'Copied', 'share.linkCopied': 'Link copied', 'share.pasteHint': 'Paste your message into the app', 'share.share': 'Share', 'share.nativeShare': 'Share via device', 'share.whatsapp': 'WhatsApp', 'share.signal': 'Signal', 'share.discord': 'Discord', 'share.mastodon': 'Mastodon', 'share.bluesky': 'Bluesky', 'share.nostr': 'Nostr', 'share.facebook': 'Facebook', 'share.x': 'X', 'share.reddit': 'Reddit', 'share.pinterest': 'Pinterest', 'share.snapchat': 'Snapchat', 'share.instagram': 'Instagram', 'share.telegram': 'Telegram', 'share.linkedin': 'LinkedIn', 'share.tumblr': 'Tumblr', 'share.email': 'Email', 'share.tiktok': 'TikTok', 'share.buttonLabel': 'Share this page',
  // Trade board
  'trade.addCard': 'Add card', 'trade.addOfferedAndWanted': 'Add at least one offered and one wanted card.', 'trade.addOneCard': 'Add at least one card first.',
  'trade.circleOnly': 'Circle only', 'trade.collector': 'Collector', 'trade.couldNotCreate': 'Could not create listing: ',
  'trade.couldNotDeleteTemplate': 'Could not delete template: ', 'trade.couldNotSaveTemplate': 'Could not save template: ', 'trade.couldNotUpdate': 'Could not update listing',
  'trade.currency': 'Currency', 'trade.enterTemplateName': 'Enter a template name', 'trade.in30days': 'In 30 days',
  'trade.in7days': 'In 7 days', 'trade.in90days': 'In 90 days', 'trade.listingExpires': 'Listing expires', 'trade.listings': 'listings',
  'trade.loadTemplate': 'Load template…', 'trade.markCompleted': 'Mark Completed', 'trade.markedCompleted': 'Marked as completed',
  'trade.markedCompletedSynced': 'Marked as completed & synced to network', 'trade.max20Cards': 'You can add a maximum of 20 cards per side.',
  'trade.negotiate': 'Negotiate', 'trade.networkSees': 'The network can see this trade is completed.', 'trade.newListingModal': 'New Trade Listing',
  'trade.noCardsAdded': 'No cards added yet', 'trade.noExpiry': 'No expiry',
  'trade.notesPlaceholder': 'Add notes about condition, shipping, or trade terms…', 'trade.offering': 'Offering',
  'trade.pdsSyncFailed': 'Saved locally, but could not sync to the AT Protocol network.', 'trade.public': 'Public',
  'trade.publishedLocal': 'Published locally', 'trade.publishedSynced': 'Published & synced to network', 'trade.publishing': 'Publishing…',
  'trade.publishListing': 'Publish Listing', 'trade.save': 'Save', 'trade.saveAsTemplate': 'Save as template',
  'trade.selectCardToOffer': 'Select card to offer', 'trade.selectCircle': 'Select a circle', 'trade.selectCircleForListing': 'Select a circle for this listing',
  'trade.selectWantedCard': 'Select wanted card', 'trade.shippingRegions': 'Shipping regions', 'trade.syncingToPds': 'Syncing to PDS…',
  'trade.templateNamePlaceholder': 'Template name', 'trade.templateSaved': 'Template saved', 'trade.trustedOnly': 'Trusted only',
  'trade.visibility': 'Visibility', 'trade.visibleToCircle': 'Visible to circle', 'trade.wants': 'Wants', 'trade.wishlistOnly': 'Wishlist matches only',
  'trade.templates': 'Templates', 'trade.useTemplate': 'Use template', 'trade.editTemplate': 'Edit', 'trade.deleteTemplate': 'Delete',
  'trade.deleteTemplateConfirm': 'Delete this template?', 'trade.templateEmpty': 'No saved templates yet',
  'trade.templateEmptySub': 'Save a template from the New Listing modal to reuse offer/want combos.', 'trade.editTemplateTitle': 'Edit Template',
  'trade.templateOffers': 'Offers', 'trade.templateWants': 'Wants', 'trade.newListingShort': 'New listing',
  // Trade templates page
  'page.tradeTemplates.title': 'Trade Templates', 'page.tradeTemplates.subtitle': 'Saved offer/want combos to post faster',
  // Portfolio
  'portfolio.range30': '30D', 'portfolio.range90': '90D', 'portfolio.range365': '1Y', 'portfolio.rangeAll': 'All',
  'portfolio.emptyWindow': 'Not enough history yet for this range — check back after more daily snapshots.',
  // Bluesky migration
  'migration.badgeLabel': 'Moved from Bluesky',
  'migration.badgeTooltip': 'This collector has moved their home base from Bluesky to SwapPulse',
  'migration.externalMigrated': 'This collector has moved to SwapPulse',
  'migration.externalNotMember': 'This collector is on Bluesky, not a SwapPulse member',
  'migration.linkedTitle': 'Bluesky Account Linked',
  'migration.linkedDesc': "You're now posting as @{handle}.",
  'migration.linkedFederating': "You're federating as @{handle}. Your posts, replies, likes, and follows are written to your own Bluesky repository.",
  'migration.linkTitle': 'Link Your Bluesky Account',
  'migration.linkDesc': 'SwapPulse federates via the AT Protocol. Link your existing Bluesky account so your posts, replies, likes, and follows are attributed to you across the network, not the shared SwapPulse bridge account.',
  'migration.linkAutoMigrate': 'When you link, SwapPulse pulls your Bluesky profile, posts, and notifications into SwapPulse, posts and pins a "I\'ve moved" announcement on your Bluesky feed, and updates your handle. You can move back anytime.',
  'migration.noAccount': "Don't have a Bluesky account yet?",
  'migration.createAtBsky': 'Create one at bsky.app',
  'migration.thenComeBack': ', then come back here to link it.',
  'migration.linkButton': 'Link Bluesky Account',
  'migration.relink': 'Re-link Account',
  'migration.contentMigratedTitle': 'Content migrated',
  'migration.contentMigratedDesc': 'Your existing posts are being moved to your Bluesky account.',
  'migration.announceTitle': 'Migration announced on Bluesky',
  'migration.announceDesc': "A 'I've moved to SwapPulse' post has been published and pinned on your Bluesky feed so followers can find you here.",
  'migration.announceFailedTitle': 'Migration announcement failed',
  'migration.announceFailedDesc': 'Your Bluesky account is linked, but the automatic announcement could not be posted. You can retry from Settings.',
  'migration.statusMigrated': 'Migrated to SwapPulse',
  'migration.statusMigratedDesc': 'Your Bluesky profile, posts, and notifications have been synced into SwapPulse. A pinned announcement is live on your Bluesky feed and your handle has been updated.',
  'migration.moveBack': 'Move back to Bluesky',
  'migration.unmoveConfirm': 'Move back to Bluesky? This will restore your original Bluesky bio, unpin and delete the migration announcement post, and remove the "Moved from Bluesky" badge from your SwapPulse profile. Your Bluesky link stays active.',
  'migration.unmovedTitle': 'Moved back to Bluesky',
  'migration.unmovedDesc': 'Your original Bluesky bio has been restored and the migration announcement has been removed.',
  'migration.unmoveFailedTitle': 'Could not move back',
  'migration.unmoveFailedDesc': 'Something went wrong reversing the migration. Please try again.',
  'migration.migratingStatus': 'Syncing your Bluesky profile and announcing your move…',
  'migration.syncingPosts': 'Syncing your Bluesky posts… ({count} so far)',
  'migration.syncComplete': 'Sync complete',
  'migration.profilePulled': 'Bluesky profile synced',
  'migration.postsBackfilled': 'Posts synced',
  'migration.notificationsImported': 'Notifications imported',
  'migration.continueSync': 'Continue syncing posts',
  'migration.syncFailedDesc': 'Some content could not be synced. You can retry from Settings.',
  'migration.rebridgingStatus': 'Migrating your existing content…',
  'migration.handleLabel': 'Your SwapPulse handle',
  'migration.handlePreview': 'Your handle will be',
  'migration.useDefaultDomain': 'Use default domain',
  'migration.useCustomDomain': 'Use a custom domain',
  'migration.customDomainNote': 'You\'ll need to add a DNS TXT record to verify ownership. We\'ll show you the exact record after you migrate.',
  'migration.handleUpdatedDesc': 'Your handle has been updated to @{handle}.',
  'migration.revertedTitle': 'Profile editing locked',
  'migration.revertedDesc': 'You moved back to Bluesky, so your SwapPulse profile is read-only. Re-migrate to SwapPulse to edit it again.',
  'migration.remigrate': 'Re-migrate to SwapPulse',
  'migration.editLocked': 'Locked',
  'migration.revertedNotice': 'Profile editing is locked because you moved back to Bluesky. Re-migrate to SwapPulse to unlock editing.',
};