// English UI strings extracted from src/lib/i18n/translations/en.js
// Used by the translate-ui-strings backend function as the source for AI translation.

export const UI_STRINGS_EN: Record<string, string> = {
  'nav.home': 'Home', 'nav.explore': 'Explore', 'nav.collection': 'Collection', 'nav.scan': 'Scan Cards',
  'nav.binders': 'Binders', 'nav.trades': 'Trade Board', 'nav.circles': 'Circles', 'nav.meetups': 'Meetups',
  'nav.live': 'Live Now', 'nav.notifications': 'Notifications', 'nav.messages': 'Messages', 'nav.more': 'More',
  'nav.trust': 'Trust', 'nav.whoToFollow': 'Who to Follow', 'nav.achievements': 'Achievements',
  'nav.challenges': 'Challenges', 'nav.packParties': 'Pack Parties', 'nav.pullOfTheWeek': 'Pull of the Week',
  'nav.packOpenings': 'Pack Openings', 'nav.market': 'Market Watch', 'nav.predictions': 'Predictions',
  'nav.grading': 'Grading', 'nav.help': 'Help & Info', 'nav.donate': 'Donate', 'nav.settings': 'Settings',
  'nav.login': 'Log in', 'nav.logout': 'Log Out', 'nav.profile': 'View profile', 'nav.admin': 'Admin',
  'nav.moderation': 'Moderation',
  'card.overview': 'Overview', 'card.discussion': 'Discussion', 'card.posts': 'Posts', 'card.reviews': 'Reviews',
  'card.trades': 'Trades', 'card.packOpenings': 'Pack Openings', 'card.addToCollection': 'Add to Collection',
  'card.wishlist': 'Wishlist', 'card.listForTrade': 'List for Trade', 'card.priceAlert': 'Price Alert',
  'card.marketPrice': 'Market Price', 'card.variants': 'Variants', 'card.weaknessResistance': 'Weakness & Resistance',
  'card.legality': 'Legality', 'card.standardLegal': 'Standard-legal', 'card.notExpanded': 'Not Expanded-legal',
  'card.attacks': 'Attacks', 'card.abilities': 'Abilities', 'card.hp': 'HP', 'card.stage': 'Stage',
  'card.evolvesFrom': 'Evolves from', 'card.illustrator': 'Illustrator', 'card.retreat': 'Retreat',
  'card.regulationMark': 'Regulation Mark', 'card.avgMarket': 'avg market', 'card.source': 'Source',
  'card.normal': 'Normal', 'card.holo': 'Holo', 'card.reverse': 'Reverse', 'card.firstEdition': '1st Edition',
  'card.promo': 'Promo', 'card.notFound': 'Card not found.', 'card.loading': 'Loading…',
  'card.weakness': 'Weakness', 'card.resistance': 'Resistance',
  'common.loading': 'Loading…', 'common.search': 'Search', 'common.follow': 'Follow', 'common.following': 'Following',
  'common.reply': 'Reply', 'common.repost': 'Repost', 'common.like': 'Like', 'common.share': 'Share',
  'common.cancel': 'Cancel', 'common.save': 'Save', 'common.delete': 'Delete', 'common.edit': 'Edit',
  'common.close': 'Close', 'common.viewOnSwapPulse': 'View on SwapPulse', 'common.fromBluesky': 'From Bluesky',
  'common.viewAll': 'View all', 'common.noResults': 'No results yet', 'common.collectors': 'collectors',
  'feed.forYou': 'For You', 'feed.freshPulls': 'Fresh Pulls', 'feed.tradeFloor': 'Trade Floor',
  'feed.showcase': 'Showcase', 'feed.quiet': 'Your feed is quiet', 'feed.followCollectors': 'Follow collectors to personalize your feed',
  'feed.discoverCollectors': 'Discover collectors', 'feed.welcome': 'Welcome to SwapPulse',
  'feed.createAccount': 'Create account', 'feed.exploreCards': 'Explore cards',
  'trending.title': 'Trending Cards', 'trending.subtitle': 'Most talked-about cards right now',
  'trending.posts': 'posts', 'lang.switch': 'Language', 'lang.interface': 'Interface language',
  'nav.terms': 'Terms', 'nav.privacy': 'Privacy', 'nav.status': 'Status',
  'feed.quietSub': 'Follow some collectors to fill your feed.',
  'feed.followCollectorsSub': "You're seeing recent posts from the community. Follow collectors to see their content first.",
  'feed.noPosts': 'No posts in this feed yet. Check back soon!',
  'feed.welcomeSub': 'Join the decentralized social network for Pokémon TCG collectors, track your collection, trade cards, and connect with the community.',
  'page.binders.title': 'Digital Binders', 'page.binders.subtitle': 'Curated showcases of prized cards',
  'page.binders.myBinders': 'My Binders', 'page.binders.discover': 'Discover', 'page.binders.new': 'New',
  'page.binders.empty.mine': 'No binders yet', 'page.binders.empty.discover': 'Nothing to discover yet',
  'page.binders.empty.mineSub': 'Create your first digital binder.',
  'page.binders.empty.discoverSub': 'Public binders from the community will appear here.',
  'page.binders.create': 'Create Binder',
  'page.collection.title': 'My Collection', 'page.collection.cardsTracked': 'cards tracked', 'page.collection.add': 'Add',
  'page.collection.tabs.cards': 'All Cards', 'page.collection.tabs.completion': 'Completion', 'page.collection.tabs.duplicates': 'Duplicates',
  'page.collection.tabs.binder': 'Binder', 'page.collection.tabs.analytics': 'Analytics', 'page.collection.tabs.importExport': 'Import / Export', 'page.collection.tabs.insurance': 'Insurance',
  'page.collection.stats.totalValue': 'Total Value', 'page.collection.stats.cards': 'Cards', 'page.collection.stats.showcased': 'Showcased',
  'page.market.title': 'Market Watch', 'page.market.subtitle': 'Track prices and your portfolio', 'page.market.sync': 'Sync now',
  'page.explore.title': 'Explore', 'page.explore.subtitle': 'Search the Pokémon TCG catalogue',
  'page.explore.cards': 'Cards', 'page.explore.people': 'People', 'page.explore.posts': 'Posts',
  'page.trades.title': 'Trade Board', 'page.trades.subtitle': 'Open trade listings', 'page.trades.newListing': 'New Listing',
  'page.trades.empty': 'No active trades', 'page.trades.emptySub': 'Create a listing to start trading.',
  'footer.tagline': 'A decentralized Pokémon TCG community',
  'footer.terms': 'Terms', 'footer.privacy': 'Privacy Policy', 'footer.help': 'Help', 'footer.status': 'Status', 'footer.explore': 'Explore', 'footer.donate': 'Donate',
  'footer.disclaimer': 'SwapPulse is a free, open-source platform. Pokémon and Pokémon TCG are trademarks of Nintendo, Game Freak, and The Pokémon Company. SwapPulse is not affiliated with or endorsed by them.',
  'footer.builtOn': '© SwapPulse - Built on the AT Protocol · Powered by TCGdex',
  'page.sets.title': 'Set Checklists', 'page.sets.subtitle': 'Track completion and download printable PDFs',
  'page.sets.signIn': 'Sign in to track your collection', 'page.sets.signInSub': 'You need a SwapPulse account to manage your set checklists and download PDFs.',
  'profile.tab.posts': 'Posts', 'profile.tab.activity': 'Activity', 'profile.tab.binder': 'Binder', 'profile.tab.collection': 'Collection',
  'profile.tab.trades': 'Trades', 'profile.tab.tradeActivity': 'Trade Activity', 'profile.tab.reputation': 'Reputation', 'profile.tab.following': 'Following',
  'profile.tab.journals': 'Journals', 'profile.tab.podcasts': 'Podcasts', 'profile.tab.crossPosting': 'Cross-Posting', 'profile.tab.privacy': 'Privacy',
  'page.trust.title': 'Trust & Vouches', 'page.trust.yourScore': 'Your Trust Score', 'page.trust.scoreSub': 'Based on incoming vouches from trusted collectors.',
  'page.trust.vouches': 'vouches', 'page.trust.mutual': 'mutual',
  'page.notifications.title': 'Notifications', 'page.notifications.subtitle': 'Trade matches, price drops and activity from across SwapPulse',
  'page.notifications.markAllRead': 'Mark all read', 'page.notifications.emptySub': 'Trade matches and price alerts will show up here.',
  'page.notifications.empty.all': 'No notifications yet', 'page.notifications.empty.unread': 'No unread notifications',
  'page.notifications.empty.mentions': 'No mentions', 'page.notifications.empty.follows': 'No new follows',
  'common.today': 'Today', 'common.earlier': 'Earlier', 'common.quote': 'Quote', 'common.report': 'Report', 'common.collector': 'Collector',
  'post.type.packPull': 'Pack Pull', 'post.type.trade': 'Trade', 'post.type.showcase': 'Showcase',
  'page.settings.title': 'Settings', 'page.settings.subtitle': 'Your self-sovereign control centre - saved to your repository',
  'settings.tab.account': 'Account', 'settings.tab.language': 'Language', 'settings.tab.privacy': 'Privacy', 'settings.tab.notifications': 'Notifications',
  'settings.tab.accessibility': 'Accessibility', 'settings.tab.advanced': 'Advanced', 'settings.tab.challenges': 'Challenges', 'settings.tab.security': 'Security',
  'settings.tab.datarights': 'Data & Rights', 'settings.tab.atprotocol': 'AT Protocol',
  'page.compose.reply': 'Reply', 'page.compose.newPost': 'New Post', 'compose.replyingTo': 'Replying to',
  'compose.placeholder.reply': 'Write your reply...', 'compose.placeholder.post': 'What did you pull today?',
  'compose.charsLeft': 'left', 'compose.altTextLabel': 'Image description (alt text)',
  'compose.altTextPlaceholder': 'Describe the card image for screen readers...',
  'compose.whoCanReply': 'Who can reply:', 'compose.whoCanSee': 'Who can see:',
  'compose.card': 'Card', 'compose.collection': 'Collection', 'compose.post': 'Post',
  'compose.selectTradeCard': 'Select card to trade', 'compose.attachCard': 'Attach a card',
  'compose.policy.everyone': 'Everyone', 'compose.policy.followers': 'Followers', 'compose.policy.mentioned': 'Mentioned', 'compose.policy.nobody': 'No one',
  'compose.scope.public': 'Public', 'compose.scope.followers': 'Followers', 'compose.scope.mentioned': 'Mentioned', 'common.followers': 'Followers',
  'page.circles.title': 'Circles', 'page.circles.subtitle': 'Curated member groups with scoped trades', 'page.circles.new': 'New circle',
  'page.circles.yourCircles': 'Your circles', 'page.circles.discover': 'Discover', 'page.circles.empty': 'No circles yet. Create the first one.',
  'page.meetups.title': 'Meetups', 'page.meetups.subtitle': 'Vouch-gated local collector meetups', 'page.meetups.new': 'New meetup',
  'page.meetups.empty': 'No meetups scheduled. Organise the first one.',
  'page.spaces.title': 'Live Streams', 'page.spaces.subtitle': 'Collectors streaming now - tap a live ring to join', 'page.spaces.goLive': 'Go Live',
  'spaces.tab.live': 'Live Now', 'spaces.tab.recordings': 'Recordings',
  'page.messages.title': 'Messages', 'page.messages.subtitle': 'Private chats with other collectors',
  'page.messages.empty': 'No conversations yet.', 'page.messages.emptySub': "Tap Message on a collector's profile to start chatting.",
  'page.messages.select': 'Select a conversation to start chatting.',
  'page.challenges.title': 'Challenges', 'page.challenges.subtitle': 'Cooperative community goals & opt-in leaderboards',
  'challenges.tab.active': 'Active', 'challenges.tab.upcoming': 'Upcoming', 'challenges.tab.completed': 'Completed', 'challenges.tab.mine': 'My Entries',
  'page.challenges.empty': 'No challenges match. Try another tab or filter.',
  'page.achievements.title': 'Achievements', 'page.achievements.subtitle': 'Proof-based, network-verified credentials, not participation trophies',
  'page.achievements.reEvaluate': 'Re-evaluate',
  'page.packs.title': 'Pack Openings', 'page.packs.subtitle': 'Live pulls from the community',
  'page.packs.empty': 'No pack openings yet', 'page.packs.emptySub': 'Share a pull from the compose box to start a thread.',
  'page.share.title': 'Shared Content', 'page.share.subtitle': 'Received from another app',
  'page.share.empty': 'Nothing shared yet', 'page.share.emptySub': 'Share a card photo into SwapPulse from your camera or gallery to see it here.',
  'page.predictions.title': 'Predictions', 'page.predictions.subtitle': 'Community sentiment polls & market predictions',
  'predictions.tab.active': 'Active', 'predictions.tab.closed': 'Resolved', 'predictions.tab.all': 'All',
  'page.donate.title': 'Support SwapPulse', 'page.donate.subtitle': 'Keep the platform free & open-source', 'page.donate.back': 'Back to app',
  'page.help.title': 'Help & Info', 'page.help.subtitle': 'What SwapPulse does, how it works, and where to get help',
  'page.status.title': 'System Status', 'status.operational': 'Operational', 'status.degraded': 'Degraded', 'status.outage': 'Outage', 'status.maintenance': 'Maintenance',
  'page.grading.title': 'Grading Submissions', 'page.grading.subtitle': 'Track your PSA, CGC, and Beckett submissions',
  'page.whoToFollow.title': 'Who to Follow', 'page.whoToFollow.subtitle': 'Collectors recommended for you',
  'page.packParties.title': 'Pack Parties', 'page.packParties.subtitle': 'Open packs together with other collectors',
  'page.pullOfTheWeek.title': 'Pull of the Week', 'page.pullOfTheWeek.subtitle': 'Vote for the best pull this week',
  'page.tradeDashboard.title': 'Trade Dashboard', 'page.tradeDashboard.subtitle': 'Your active trades and trade history',
  'page.tradeStatusBoard.title': 'Trade Status Board', 'page.tradeStatusBoard.subtitle': 'Live trade activity across the community',
  'page.tradeThread.title': 'Negotiation', 'page.tradeThread.notFound': 'Trade not found', 'page.tradeThread.backToBoard': 'Back to Trade Board', 'page.tradeThread.board': 'Board', 'page.tradeThread.subtitle': 'Negotiate a trade',
  'page.hashtag.title': 'Hashtag', 'page.hashtag.subtitle': 'Posts tagged with this hashtag', 'hashtag.followTag': 'Follow tag',
  'page.journal.title': 'Journal', 'page.journal.loading': 'Loading journal…', 'page.journal.notFound': 'Journal not found',
  'userProfile.back': 'Back', 'userProfile.noOnSiteActivity': 'No on-site activity, this collector posts on Bluesky.',
  'userProfile.viewOnBluesky': 'View on Bluesky', 'userProfile.tradeHistoryMembers': 'Trade history is only available for SwapPulse members.',
  'userProfile.sharedCollectionsMembers': 'Shared collections are only available for SwapPulse members.',
  'userProfile.noPostsBluesky': 'No posts found on Bluesky.', 'userProfile.noPostsYet': 'No posts yet.',
  'page.terms.title': 'Terms of Service', 'page.privacy.title': 'Privacy Policy',
  'card.dataUnavailable': 'Card data unavailable', 'card.noPriceData': 'No price data', 'card.low': 'Low',
  'common.fromWeb': 'From the web', 'home.cardOfTheDay': 'Card of the Day', 'home.cardOfTheDaySub': 'Featured for notable price movement',
  'auth.guestBrowse': 'Browsing as a guest.', 'auth.guestLoginAction': 'to post, trade, and interact.', 'common.dismiss': 'Dismiss',
  'sidebar.onlineNow': 'Online now', 'sidebar.collectorsActive': 'Collectors active in the last 2 minutes.',
  'sidebar.trendingTopics': 'Trending Topics', 'sidebar.cardsLabel': 'Cards', 'sidebar.hashtagsLabel': 'Hashtags', 'sidebar.keywordsLabel': 'Keywords',
  'common.you': 'You', 'stories.yourStory': 'Your story',
  'sidebar.yourPortfolio': 'Your Portfolio', 'sidebar.activeTrades': 'Active Trades', 'sidebar.trendingCards': 'Trending Cards',
  'sidebar.offering': 'Offering', 'sidebar.wants': 'Wants', 'sidebar.cards': 'cards',
  'sidebar.mutualVouch': 'mutual vouch', 'sidebar.mutualVouches': 'mutual vouches', 'sidebar.trustScore': 'Trust',
  'sidebar.copyright': '© SwapPulse - Built on the AT Protocol · Powered by TCGdex',
  'toast.following': 'Following', 'toast.couldNotFollow': 'Could not follow',
  'profile.editProfile': 'Edit profile', 'profile.collector': 'Collector', 'profile.trustedTrader': 'Trusted Trader',
  'profile.binderEmpty': 'Your binder is empty. Add cards to your collection.', 'profile.portfolioValue': 'Portfolio value:',
  'profile.myCollectionNetwork': 'My Collection on the Network', 'profile.myTradesNetwork': 'My Trades on the Network', 'notifications.refresh': 'Refresh notifications',
  'binder.deleteConfirm': 'Delete this binder?', 'binder.notFound': 'Binder not found.', 'binder.edit': 'Edit',
  'trust.networkSubtitle': 'Vouch-based reputation across the community', 'trust.revokeConfirm': 'Revoke this vouch? It will no longer count towards their trust score.',
  'trust.rel.trade_partner': 'Trade Partner', 'trust.rel.repeat_trader': 'Repeat Trader', 'trust.rel.personal_acquaintance': 'Personal', 'trust.rel.community_member': 'Community',
  'trust.vouchesForYou': 'Vouches for you', 'trust.noVouchesForYou': 'No one has vouched for you yet.',
  'trust.youVouchedFor': 'You vouched for', 'trust.noOutgoingVouches': "You haven't vouched for anyone yet.", 'trust.revoked': 'Revoked', 'trust.revoke': 'Revoke',
  'circles.theme.general': 'General', 'circles.theme.vintage': 'Vintage', 'circles.theme.competitive': 'Competitive', 'circles.theme.shiny': 'Shiny', 'circles.theme.investment': 'Investment', 'circles.theme.local_region': 'Local', 'circles.theme.artist': 'Artist',
  'circles.curator': 'Curator', 'circles.member': 'Member', 'circles.members': 'members',
  'meetups.tbd': 'TBD', 'meetups.vouches': 'vouches',
  'predictions.newPoll': 'New poll', 'predictions.empty.active': 'No active polls. Create the first market prediction.', 'predictions.empty.all': 'Nothing here yet.',
  'grading.new': 'New', 'grading.empty': 'No grading submissions yet', 'grading.emptySub': "Track cards you've sent to PSA, BGS, CGC or ACE - status, tracking and grades.", 'grading.add': 'Add submission', 'grading.noTracking': 'no tracking',
  'grading.status.submitted': 'Submitted', 'grading.status.in_progress': 'In Progress', 'grading.status.graded': 'Graded', 'grading.status.returned': 'Returned', 'grading.status.rejected': 'Rejected',
  'grading.declared': 'Declared:', 'grading.expected': 'Expected:', 'grading.sent': 'Sent:', 'grading.advance': 'Advance status', 'grading.gradePlaceholder': 'Grade e.g. PSA 10',
  'achievements.evaluateError': 'Could not evaluate achievements', 'achievements.of': 'of', 'achievements.summary': 'credentials unlocked. Each is a state-dependent proof verified against your on-chain activity, revoked if the underlying proof no longer holds (after a 24h grace period).',
  'challenges.filter.all': 'All', 'challenges.filter.collective': 'Collective', 'challenges.filter.competitive': 'Competitive', 'challenges.filter.circle': 'Circle-Scoped', 'challenges.loadError': 'Failed to load',
  'spaces.all': 'All', 'spaces.sort.viewers': 'Viewers', 'spaces.sort.recent': 'Recent', 'spaces.noStreamsPlatform': 'No live streams on this platform right now.', 'spaces.noStreamsLive': 'No streams live right now', 'spaces.beFirst': 'Be the first to go live!', 'spaces.noRecordings': 'No recordings yet.',
  'share.addToCollection': 'Add to Collection', 'share.createPost': 'Create Post', 'share.dismiss': 'Dismiss',
  'tradeStatus.open': 'Open', 'tradeStatus.negotiating': 'Negotiating', 'tradeStatus.pendingShip': 'Pending Ship', 'tradeStatus.completed': 'Completed', 'tradeStatus.cancelled': 'Cancelled',
  'tradeStatus.searchPlaceholder': 'Search cards or collector…', 'tradeStatus.all': 'All', 'tradeStatus.mine': 'Mine', 'tradeStatus.noTradesFound': 'No trades found', 'tradeStatus.noTradesMine': 'You have no trades yet.', 'tradeStatus.noTradesBoard': 'No trades on the board yet.', 'tradeStatus.noTrades': 'No trades', 'tradeStatus.cards': 'Cards',
  'tradeThread.sendError': 'Could not send', 'tradeThread.markPendingShip': 'Mark Pending Ship', 'tradeThread.markCompleted': 'Mark Completed', 'tradeThread.statusError': 'Could not update status', 'tradeThread.watchError': 'Could not update watch status', 'tradeThread.watching': 'Watching', 'tradeThread.watchTrade': 'Watch this trade', 'tradeThread.watchSub': 'Get notified on updates and completion.', 'tradeThread.disputeFiled': 'Dispute filed', 'tradeThread.reportDispute': 'Report a Dispute', 'tradeThread.disputeSub': 'Flag for moderation if something went wrong with the cards.', 'tradeThread.status': 'Status', 'tradeThread.cancelTrade': 'Cancel trade', 'tradeThread.startConversation': 'Start the conversation - ask about condition, shipping, or terms.', 'tradeThread.messagePlaceholder': 'Message…',
  'tradeDashboard.active': 'Active', 'tradeDashboard.pendingShip': 'Pending Ship', 'tradeDashboard.completed': 'Completed', 'tradeDashboard.cancelled': 'Cancelled', 'tradeDashboard.signIn': 'Sign in to view your dashboard', 'tradeDashboard.goToLogin': 'Go to login', 'tradeDashboard.myActiveTrades': 'My Active Trades', 'tradeDashboard.noActive': 'No active trades.', 'tradeDashboard.browseBoard': 'Browse the board', 'tradeDashboard.toStartOne': 'to start one.', 'tradeDashboard.watching': 'Watching', 'tradeDashboard.notWatching': 'Not watching any trades. Open a trade and tap the bell to get notified.',
  'binder.editTitle': 'Edit Binder', 'binder.newTitle': 'New Binder', 'binder.editSubtitle': 'Arrange your prized cards into pages', 'binder.save': 'Save', 'binder.saveError': 'Failed to save binder', 'binder.titlePlaceholder': "Binder title (e.g. 'My Holos')", 'binder.descPlaceholder': 'Short description...', 'binder.theme': 'Theme', 'binder.visibility': 'Visibility', 'binder.visibilityPublic': 'Public', 'binder.visibilityFollowers': 'Followers', 'binder.visibilityPrivate': 'Private', 'binder.coverPlaceholder': 'Cover image URL (optional)', 'binder.page': 'Page', 'binder.captionPlaceholder': 'caption', 'binder.addPage': 'Add page',
  'admin.title': 'Admin', 'admin.subtitle': 'Production readiness dashboard', 'admin.adminsOnly': 'Admins only', 'admin.noAccess': "You don't have access to this page.", 'admin.loadError': 'Failed to load metrics',
  'moderation.staffOnly': 'Staff only', 'moderation.staffOnlySub': 'The moderator dashboard is restricted to staff and administrators.', 'moderation.title': 'Moderator Dashboard', 'moderation.subtitle': 'Review flagged posts and apply moderation decisions', 'moderation.refresh': 'Refresh', 'moderation.tab.posts': 'Flagged Posts', 'moderation.tab.disputes': 'Trade Disputes', 'moderation.tab.enforcement': 'Account Enforcement', 'moderation.tab.bots': 'Bot Protection', 'moderation.hideFilters': 'Hide Filters', 'moderation.showFilters': 'Show Filters',
};