// Shared WebAuthn utilities used by registration, login and wallet ceremonies.
// Challenges are random, HMAC-authenticated, stored server-side, short-lived,
// and single-use. This prevents replay even for authenticators that do not
// implement signature counters.

import { verifyAuthenticationResponse } from 'npm:@simplewebauthn/server@10';

const encoder = new TextEncoder();
const decoder = new TextDecoder();

function base64UrlToBytes(base64url: string): Uint8Array {
  const padded = base64url.replace(/-/g, '+').replace(/_/g, '/');
  const pad = padded.length % 4;
  const b64 = pad ? padded + '='.repeat(4 - pad) : padded;
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function bytesToBase64Url(bytes: Uint8Array | ArrayBuffer): string {
  const arr = bytes instanceof ArrayBuffer ? new Uint8Array(bytes) : bytes;
  let binary = '';
  for (let i = 0; i < arr.length; i++) binary += String.fromCharCode(arr[i]);
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

async function hmacKey(secret: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    'raw',
    encoder.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign', 'verify'],
  );
}

// Generate a random challenge and its HMAC signature.
export async function generateSignedChallenge(secret: string): Promise<{
  challenge: string;
  signature: string;
}> {
  const challengeBytes = new Uint8Array(32);
  crypto.getRandomValues(challengeBytes);
  const challenge = bytesToBase64Url(challengeBytes);
  const key = await hmacKey(secret);
  const sig = await crypto.subtle.sign('HMAC', key, encoder.encode(challenge));
  const signature = bytesToBase64Url(sig);
  return { challenge, signature };
}

// Verify that a challenge+signature pair was generated by this server.
export async function verifySignedChallenge(
  secret: string,
  challenge: string,
  signature: string,
): Promise<boolean> {
  if (!challenge || !signature) return false;
  try {
    const key = await hmacKey(secret);
    const sigBytes = base64UrlToBytes(signature);
    const valid = await crypto.subtle.verify('HMAC', key, sigBytes, encoder.encode(challenge));
    return valid;
  } catch {
    return false;
  }
}

const WEBAUTHN_ALLOWED_ORIGINS = new Set([
  'https://swappulse.org',
  'https://www.swappulse.org',
  'http://localhost:3000',
  'http://localhost:5173',
]);

function addConfiguredOrigin(): void {
  const configured = Deno.env.get('WIX_CHECKOUT_APP_URL') || Deno.env.get('APP_URL') || '';
  if (!configured) return;
  try {
    const u = new URL(configured);
    if (u.protocol === 'https:' || (u.protocol === 'http:' && ['localhost', '127.0.0.1'].includes(u.hostname))) {
      WEBAUTHN_ALLOWED_ORIGINS.add(u.origin);
    }
  } catch {}
}
addConfiguredOrigin();

// Resolve WebAuthn origin/RP only from an explicit allowlist. Request headers
// are caller-controlled and therefore may select only an already-approved
// origin, never create a new trusted origin dynamically.
export function getRpConfig(req: Request): { origin: string; rpId: string } | null {
  const candidates = [req.headers.get('Origin'), req.headers.get('Referer')];
  for (const candidate of candidates) {
    if (!candidate) continue;
    try {
      const u = new URL(candidate);
      if (WEBAUTHN_ALLOWED_ORIGINS.has(u.origin)) return { origin: u.origin, rpId: u.hostname };
    } catch {}
  }

  const host = req.headers.get('Host');
  if (host) {
    const hostname = host.split(':')[0];
    const protocol = ['localhost', '127.0.0.1'].includes(hostname) ? 'http' : 'https';
    const candidate = `${protocol}://${host}`;
    if (WEBAUTHN_ALLOWED_ORIGINS.has(candidate)) return { origin: candidate, rpId: hostname };
  }
  return null;
}

async function sha256Base64Url(value: string): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', encoder.encode(value));
  return bytesToBase64Url(digest);
}

export async function issueWebAuthnChallenge(
  svc: any,
  secret: string,
  purpose: 'authentication' | 'registration' | 'wallet',
  subject: string,
  rpConfig: { origin: string; rpId: string },
  ttlMs = 5 * 60 * 1000,
): Promise<{ challenge: string; signature: string }> {
  const signed = await generateSignedChallenge(secret);
  const challengeHash = await sha256Base64Url(signed.challenge);
  await svc.entities.WebAuthnChallenge.create({
    challenge_hash: challengeHash,
    purpose,
    subject,
    origin: rpConfig.origin,
    rp_id: rpConfig.rpId,
    expires_at: new Date(Date.now() + ttlMs).toISOString(),
  });
  return signed;
}

export async function consumeWebAuthnChallenge(
  svc: any,
  secret: string,
  challenge: string,
  signature: string,
  purpose: 'authentication' | 'registration' | 'wallet',
  subject: string,
  rpConfig: { origin: string; rpId: string },
): Promise<boolean> {
  if (!(await verifySignedChallenge(secret, challenge, signature))) return false;
  const challengeHash = await sha256Base64Url(challenge);
  const rows = await svc.entities.WebAuthnChallenge
    .filter({ challenge_hash: challengeHash, purpose, subject }, '-created_date', 5)
    .catch(() => []);
  const row = (rows || []).find((r: any) =>
    !r.used_at &&
    r.origin === rpConfig.origin &&
    r.rp_id === rpConfig.rpId &&
    r.expires_at &&
    new Date(r.expires_at).getTime() > Date.now()
  );
  if (!row) return false;

  // Consume before credential verification. A failed assertion burns only its
  // own challenge, preventing replay at the cost of requiring a fresh ceremony.
  await svc.entities.WebAuthnChallenge.update(row.id, { used_at: new Date().toISOString() });
  return true;
}

// Verify a wallet-unlock passkey assertion. Used by send-crypto,
// execute-conversion, and execute-usdc-to-fiat to consistently verify the
// WebAuthn assertion against the user's enrolled credentials. Centralises
// the RP-ID/origin extraction (getRpConfig), challenge-signature check, and
// public-key format conversion so every wallet unlock path matches the
// registration and login flows exactly.
export async function verifyWalletPasskey(
  req: Request,
  svc: any,
  userId: string,
  assertion: any,
  challenge: string,
  challengeSignature: string,
): Promise<{ verified: boolean; error?: string; status?: number }> {
  const rpConfig = getRpConfig(req);
  if (!rpConfig) return { verified: false, error: 'Could not determine origin', status: 400 };

  const sigValid = await consumeWebAuthnChallenge(
    svc,
    process.env.BACKEND_FUNCTION_SECRET!,
    challenge,
    challengeSignature,
    'wallet',
    userId,
    rpConfig,
  );
  if (!sigValid) return { verified: false, error: 'Invalid challenge', status: 403 };

  const creds = await svc.entities.WebAuthnCredential
    .filter({ user_id: userId }, '-created_date', 50).catch(() => []);
  const validCreds = creds.filter((c: any) => c.credential_id);
  if (!validCreds.length) return { verified: false, error: 'No passkey enrolled', status: 400 };

  let lastError = '';
  for (const cred of validCreds) {
    try {
      const result = await verifyAuthenticationResponse({
        response: assertion,
        expectedChallenge: challenge,
        expectedOrigin: rpConfig.origin,
        expectedRPID: rpConfig.rpId,
        authenticator: {
          credentialID: cred.credential_id,
          credentialPublicKey: base64UrlToUint8Array(cred.public_key),
          // Counterless platform authenticators may legitimately remain at 0.
          // Replay protection is enforced independently by the server-side,
          // expiring, single-use WebAuthn challenge.
          counter: 0,
        },
      });
      if (result.verified) {
        // Store the authenticator's reported counter directly. Many platform
        // authenticators (Touch ID, Face ID, Windows Hello) don't support
        // counters and always report 0; the `||` fallback to `cred.counter + 1`
        // would store 1, causing every subsequent auth to fail with
        // "Response counter value 0 was lower than expected 1".
        const newCounter = result.authenticationInfo?.newCounter;
        await svc.entities.WebAuthnCredential.update(cred.id, {
          counter: typeof newCounter === 'number' ? newCounter : (cred.counter || 0),
        });
        return { verified: true };
      }
    } catch (e: any) {
      lastError = e?.message || String(e);
      console.error('[verifyWalletPasskey] cred verification error:', lastError);
    }
  }
  console.error('[verifyWalletPasskey] FAILED', {
    rpId: rpConfig.rpId,
    origin: rpConfig.origin,
    credCount: validCreds.length,
    lastError,
    assertionOrigin: assertion?.response?.clientExtensionResults,
    assertionRpId: assertion?.response?.rpId,
  });
  // Include diagnostic detail in the error so the frontend can surface it
  // during debugging (RP mismatch is the most common cause of 403s).
  return {
    verified: false,
    error: `Passkey verification failed (rpId=${rpConfig.rpId}, origin=${rpConfig.origin}, creds=${validCreds.length}, err=${lastError || 'no-match'})`,
    status: 403,
  };
}

// Convert a base64url string to a Uint8Array (for @simplewebauthn/server interop).
export function base64UrlToUint8Array(base64url: string): Uint8Array {
  return base64UrlToBytes(base64url);
}

// Convert a Uint8Array to a base64url string.
export function uint8ArrayToBase64Url(bytes: Uint8Array): string {
  return bytesToBase64Url(bytes);
}