// Shared WebAuthn utilities — used by the webauthn-* backend functions for
// stateless challenge tracking and origin/RP-ID extraction.
//
// Challenge tracking: WebAuthn requires the server to verify that the
// challenge in the client's response matches the one it sent. Since Base44
// backend functions are stateless, we use an HMAC-signed challenge: the
// server generates a random challenge, signs it with BACKEND_FUNCTION_SECRET,
// and returns both to the client. When the client sends back the attestation/
// assertion plus the signed challenge, the server verifies the HMAC signature
// before passing the challenge to @simplewebauthn/server's verify function.

import { verifyAuthenticationResponse } from 'npm:@simplewebauthn/server@10';

const encoder = new TextEncoder();
const decoder = new TextDecoder();

function base64UrlToBytes(base64url: string): Uint8Array {
  const padded = base64url.replace(/-/g, '+').replace(/_/g, '/');
  const pad = padded.length % 4;
  const b64 = pad ? padded + '='.repeat(4 - pad) : padded;
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function bytesToBase64Url(bytes: Uint8Array | ArrayBuffer): string {
  const arr = bytes instanceof ArrayBuffer ? new Uint8Array(bytes) : bytes;
  let binary = '';
  for (let i = 0; i < arr.length; i++) binary += String.fromCharCode(arr[i]);
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

async function hmacKey(secret: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    'raw',
    encoder.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign', 'verify'],
  );
}

// Generate a random challenge and its HMAC signature.
export async function generateSignedChallenge(secret: string): Promise<{
  challenge: string;
  signature: string;
}> {
  const challengeBytes = new Uint8Array(32);
  crypto.getRandomValues(challengeBytes);
  const challenge = bytesToBase64Url(challengeBytes);
  const key = await hmacKey(secret);
  const sig = await crypto.subtle.sign('HMAC', key, encoder.encode(challenge));
  const signature = bytesToBase64Url(sig);
  return { challenge, signature };
}

// Verify that a challenge+signature pair was generated by this server.
export async function verifySignedChallenge(
  secret: string,
  challenge: string,
  signature: string,
): Promise<boolean> {
  if (!challenge || !signature) return false;
  try {
    const key = await hmacKey(secret);
    const sigBytes = base64UrlToBytes(signature);
    const valid = await crypto.subtle.verify('HMAC', key, sigBytes, encoder.encode(challenge));
    return valid;
  } catch {
    return false;
  }
}

// Extract the origin and RP ID from the request headers.
// The RP ID must be a registrable domain suffix of the origin.
export function getRpConfig(req: Request): { origin: string; rpId: string } | null {
  const origin = req.headers.get('Origin') || req.headers.get('Referer');
  if (origin) {
    try {
      const url = new URL(origin);
      return { origin: url.origin, rpId: url.hostname };
    } catch {}
  }
  // Fallback: construct from Host header when Origin/Referer are absent
  // (some proxies or preview environments strip the Origin header).
  const host = req.headers.get('Host');
  if (host) {
    const protocol = host.startsWith('localhost') || host.startsWith('127.0.0.1') ? 'http' : 'https';
    return { origin: `${protocol}://${host}`, rpId: host.split(':')[0] };
  }
  return null;
}

// Verify a wallet-unlock passkey assertion. Used by send-crypto,
// execute-conversion, and execute-usdc-to-fiat to consistently verify the
// WebAuthn assertion against the user's enrolled credentials. Centralises
// the RP-ID/origin extraction (getRpConfig), challenge-signature check, and
// public-key format conversion so every wallet unlock path matches the
// registration and login flows exactly.
export async function verifyWalletPasskey(
  req: Request,
  svc: any,
  userId: string,
  assertion: any,
  challenge: string,
  challengeSignature: string,
): Promise<{ verified: boolean; error?: string; status?: number }> {
  const rpConfig = getRpConfig(req);
  if (!rpConfig) return { verified: false, error: 'Could not determine origin', status: 400 };

  const sigValid = await verifySignedChallenge(
    process.env.BACKEND_FUNCTION_SECRET!,
    challenge,
    challengeSignature,
  );
  if (!sigValid) return { verified: false, error: 'Invalid challenge', status: 403 };

  const creds = await svc.entities.WebAuthnCredential
    .filter({ user_id: userId }, '-created_date', 50).catch(() => []);
  const validCreds = creds.filter((c: any) => c.credential_id);
  if (!validCreds.length) return { verified: false, error: 'No passkey enrolled', status: 400 };

  for (const cred of validCreds) {
    try {
      const result = await verifyAuthenticationResponse({
        response: assertion,
        expectedChallenge: challenge,
        expectedOrigin: rpConfig.origin,
        expectedRPID: rpConfig.rpId,
        authenticator: {
          credentialID: cred.credential_id,
          credentialPublicKey: base64UrlToUint8Array(cred.public_key),
          counter: cred.counter || 0,
        },
      });
      if (result.verified) {
        await svc.entities.WebAuthnCredential.update(cred.id, {
          counter: result.authenticationInfo?.newCounter || cred.counter + 1,
        });
        return { verified: true };
      }
    } catch {}
  }
  return { verified: false, error: 'Passkey verification failed', status: 403 };
}

// Convert a base64url string to a Uint8Array (for @simplewebauthn/server interop).
export function base64UrlToUint8Array(base64url: string): Uint8Array {
  return base64UrlToBytes(base64url);
}

// Convert a Uint8Array to a base64url string.
export function uint8ArrayToBase64Url(bytes: Uint8Array): string {
  return bytesToBase64Url(bytes);
}