// Shared WebAuthn utilities — used by the webauthn-* backend functions for
// stateless challenge tracking and origin/RP-ID extraction.
//
// Challenge tracking: WebAuthn requires the server to verify that the
// challenge in the client's response matches the one it sent. Since Base44
// backend functions are stateless, we use an HMAC-signed challenge: the
// server generates a random challenge, signs it with BACKEND_FUNCTION_SECRET,
// and returns both to the client. When the client sends back the attestation/
// assertion plus the signed challenge, the server verifies the HMAC signature
// before passing the challenge to @simplewebauthn/server's verify function.

const encoder = new TextEncoder();
const decoder = new TextDecoder();

function base64UrlToBytes(base64url: string): Uint8Array {
  const padded = base64url.replace(/-/g, '+').replace(/_/g, '/');
  const pad = padded.length % 4;
  const b64 = pad ? padded + '='.repeat(4 - pad) : padded;
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function bytesToBase64Url(bytes: Uint8Array | ArrayBuffer): string {
  const arr = bytes instanceof ArrayBuffer ? new Uint8Array(bytes) : bytes;
  let binary = '';
  for (let i = 0; i < arr.length; i++) binary += String.fromCharCode(arr[i]);
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

async function hmacKey(secret: string): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    'raw',
    encoder.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign', 'verify'],
  );
}

// Generate a random challenge and its HMAC signature.
export async function generateSignedChallenge(secret: string): Promise<{
  challenge: string;
  signature: string;
}> {
  const challengeBytes = new Uint8Array(32);
  crypto.getRandomValues(challengeBytes);
  const challenge = bytesToBase64Url(challengeBytes);
  const key = await hmacKey(secret);
  const sig = await crypto.subtle.sign('HMAC', key, encoder.encode(challenge));
  const signature = bytesToBase64Url(sig);
  return { challenge, signature };
}

// Verify that a challenge+signature pair was generated by this server.
export async function verifySignedChallenge(
  secret: string,
  challenge: string,
  signature: string,
): Promise<boolean> {
  if (!challenge || !signature) return false;
  try {
    const key = await hmacKey(secret);
    const sigBytes = base64UrlToBytes(signature);
    const valid = await crypto.subtle.verify('HMAC', key, sigBytes, encoder.encode(challenge));
    return valid;
  } catch {
    return false;
  }
}

// Extract the origin and RP ID from the request headers.
// The RP ID must be a registrable domain suffix of the origin.
export function getRpConfig(req: Request): { origin: string; rpId: string } | null {
  const origin = req.headers.get('Origin') || req.headers.get('Referer');
  if (!origin) return null;
  try {
    const url = new URL(origin);
    return { origin: url.origin, rpId: url.hostname };
  } catch {
    return null;
  }
}

// Convert a base64url string to a Uint8Array (for @simplewebauthn/server interop).
export function base64UrlToUint8Array(base64url: string): Uint8Array {
  return base64UrlToBytes(base64url);
}

// Convert a Uint8Array to a base64url string.
export function uint8ArrayToBase64Url(bytes: Uint8Array): string {
  return bytesToBase64Url(bytes);
}