import React from 'react';
import { Image } from '@/components/ui/image';

const LOGO_URL =
  'https://media.base44.com/images/public/6a63d9d64a4d65d370c70892/2087a0265_a_transparent_version_of_the_socialpulse_logo_a_digital_pulse_line_forming_an_s1.png';

// Visual preview of the SwapPulse username NFT: the platform logo with the
// collector's handle overlaid at the top and their display name + member-since
// date at the bottom. Mirrors the SVG generated by the
// username-nft-metadata backend function.
export default function UsernameNftPreview({ handle, displayName, memberSince }) {
  const name = displayName || handle;
  const since = memberSince
    ? new Date(memberSince).toLocaleDateString('en-US', { month: 'long', year: 'numeric' })
    : '';

  return (
    <div className="relative aspect-square w-full max-w-[220px] overflow-hidden rounded-xl bg-black shadow-raised">
      <Image
        src={LOGO_URL}
        fittingType="fill"
        className="absolute inset-0 h-full w-full opacity-85"
        alt="SwapPulse logo"
      />
      {/* Top gradient strip with username */}
      <div className="absolute inset-x-0 top-0 h-[22%] bg-gradient-to-b from-black/95 to-transparent" />
      <p className="absolute top-3 left-0 right-0 text-center text-lg font-extrabold text-amber-400">
        @{handle}
      </p>
      {/* Bottom gradient strip with display name + member since */}
      <div className="absolute inset-x-0 bottom-0 h-[25%] bg-gradient-to-t from-black/95 to-transparent" />
      <p className="absolute bottom-7 left-0 right-0 truncate px-2 text-center text-sm font-semibold text-white">
        {name}
      </p>
      {since && (
        <p className="absolute bottom-2 left-0 right-0 text-center text-[10px] text-gray-400">
          Member since {since}
        </p>
      )}
    </div>
  );
}