#!/usr/bin/env bash
set -euo pipefail
set +x

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CHAIN_ROOT="$(cd "$HERE/.." && pwd)"
MANIFEST="${SWAPPULSE_DEPLOYMENT_MANIFEST:-$CHAIN_ROOT/deployments/swappulse-testnet.json}"
OUT="${SWAPPULSE_TX_RELAY_ENV_FILE:-$HERE/.env.relay}"
NODE_BIN="${NODE_BIN:-node}"

if [[ ! -f "$MANIFEST" ]]; then
  echo "Deployment manifest not found: $MANIFEST" >&2
  echo "Deploy the verified contracts first with ./deploy-contracts.sh" >&2
  exit 1
fi

if ! command -v "$NODE_BIN" >/dev/null 2>&1 && [[ ! -x "$NODE_BIN" ]]; then
  echo "NODE_BIN does not point to an executable Node.js runtime: $NODE_BIN" >&2
  exit 1
fi

existing_token=""
if [[ -f "$OUT" ]]; then
  existing_token="$(awk -F= '$1 == "RELAY_TOKEN" { sub(/^RELAY_TOKEN=/, ""); print; exit }' "$OUT" || true)"
fi

relay_token="${SWAPPULSE_TX_RELAY_TOKEN:-$existing_token}"
if [[ -z "$relay_token" ]]; then
  relay_token="$("$NODE_BIN" -e "process.stdout.write(require('node:crypto').randomBytes(32).toString('hex'))")"
fi
if (( ${#relay_token} < 32 )); then
  echo "Relay token must be at least 32 characters." >&2
  exit 1
fi

mapfile -t manifest_values < <(
  MANIFEST="$MANIFEST" "$NODE_BIN" --input-type=module <<'NODE'
import fs from 'node:fs';
const manifest = JSON.parse(fs.readFileSync(process.env.MANIFEST, 'utf8'));
if (Number(manifest.schema_version) !== 1) throw new Error('Unsupported deployment manifest schema_version');
if (manifest.network !== 'SWAPPULSE_TESTNET') throw new Error('Manifest is not for SWAPPULSE_TESTNET');
const hex = (value, name, allowZero = false) => {
  const raw = String(value ?? '').trim().toLowerCase();
  if (!/^0x[0-9a-f]+$/.test(raw)) throw new Error(`${name} must be 0x-prefixed hex`);
  const n = BigInt(raw);
  if ((!allowZero && n === 0n) || n < 0n) throw new Error(`${name} is invalid`);
  return `0x${n.toString(16)}`;
};
const accountClassHash = hex(manifest.account_class_hash, 'account_class_hash');
const recoveryController = hex(manifest.recovery_controller ?? '0x0', 'recovery_controller', true);
const delay = Number(manifest.recovery_delay_seconds ?? 172800);
if (!Number.isInteger(delay) || delay < 0 || delay > 2_592_000) throw new Error('Invalid recovery_delay_seconds');
console.log(accountClassHash);
console.log(recoveryController);
console.log(delay);
NODE
)

ACCOUNT_CLASS_HASH="${manifest_values[0]:-}"
RECOVERY_CONTROLLER="${manifest_values[1]:-}"
RECOVERY_DELAY_SECONDS="${manifest_values[2]:-}"
if [[ -z "$ACCOUNT_CLASS_HASH" || -z "$RECOVERY_CONTROLLER" || -z "$RECOVERY_DELAY_SECONDS" ]]; then
  echo "Could not read relay policy from deployment manifest." >&2
  exit 1
fi

tmp="${OUT}.tmp.$$"
umask 077
cat > "$tmp" <<EOF
# Generated by configure-tx-relay.sh from the verified public deployment manifest.
# Contains the private relay bearer token. Never commit or print this file.
RELAY_TOKEN=$relay_token
ACCOUNT_CLASS_HASH=$ACCOUNT_CLASS_HASH
RECOVERY_CONTROLLER=$RECOVERY_CONTROLLER
RECOVERY_DELAY_SECONDS=$RECOVERY_DELAY_SECONDS
DEPLOY_MINT_AMOUNT=${SWAPPULSE_DEPLOY_MINT_AMOUNT:-5000000000000000}
RATE_LIMIT_PER_MINUTE=${SWAPPULSE_TX_RELAY_RATE_LIMIT:-60}
EOF
chmod 600 "$tmp"
mv "$tmp" "$OUT"
chmod 600 "$OUT"

echo "SwapPulse provisioning relay configuration written securely: $OUT"
echo "Mode: $(stat -c '%a' "$OUT" 2>/dev/null || stat -f '%Lp' "$OUT")"
echo "Account class: $ACCOUNT_CLASS_HASH"
echo "Recovery controller: $RECOVERY_CONTROLLER"
echo "Recovery delay: $RECOVERY_DELAY_SECONDS seconds"
echo "Bearer token was generated/reused but is intentionally not printed."
echo "Next: docker compose --profile provisioning up -d --build tx-relay"
echo "Then copy the relay HTTPS URL and RELAY_TOKEN into the Base44 server secrets SWAPPULSE_TX_RELAY_URL and SWAPPULSE_TX_RELAY_TOKEN."
