// Public blockchain explorer copy. Every user-facing string for /chain/ lives
// here so the explorer never depends on hard-coded English in its components.

const en = {
  'nav.chainExplorer': 'Chain Explorer',
  'nav.chainWallet': 'SwapPulse Wallet',
  'footer.chainExplorer': 'Chain Explorer',
  'footer.github': 'GitHub',
  'footer.githubNewTab': 'Open the SwapPulse GitHub repository in a new tab',
  'admin.publicExplorerUrl': 'Public explorer URL',
  'lang.change': 'Change language',
  'lang.select': 'Select language',
  'explorer.seoTitle': 'SwapPulse Chain Explorer',
  'explorer.seoDescription': 'Explore SwapPulse Testnet blocks, transactions and smart-contract addresses in clear, straightforward language.',
  'explorer.title': 'SwapPulse Chain Explorer',
  'explorer.networkBadge': 'SwapPulse Testnet',
  'explorer.backToSwapPulse': 'Back to SwapPulse',
  'explorer.latestTransactions': 'Latest transactions',
  'explorer.indexedActivity': 'SwapPulse-indexed activity',
  'explorer.indexedActivityHelp': 'Public transaction hashes that SwapPulse has already linked to this smart account. This is useful wallet history, not a claim of complete archive indexing.',
  'explorer.noIndexedActivity': 'No SwapPulse-indexed transactions are available for this address yet.',
  'explorer.openWallet': 'Open SwapPulse Wallet',
  'explorer.subtitle': 'See what is happening on SwapPulse Testnet without needing to understand blockchain jargon.'
  'explorer.readOnlyNotice': 'This explorer is read-only. It shows public blockchain data and cannot move funds or change your account.',
  'explorer.searchLabel': 'Find a block, transaction or address',
  'explorer.searchPlaceholder': 'Enter a block number or 0x… identifier',
  'explorer.searchHelp': 'You can paste a block number, transaction hash, block hash, contract address, or a full SwapPulse explorer link.',
  'explorer.searchButton': 'Search',
  'explorer.refresh': 'Refresh',
  'explorer.loading': 'Loading blockchain data…',
  'explorer.latestBlocks': 'Latest blocks',
  'explorer.latestBlock': 'Latest block',
  'explorer.chainId': 'Chain ID',
  'explorer.rpcVersion': 'RPC version',
  'explorer.network': 'Network',
  'explorer.block': 'Block',
  'explorer.transaction': 'Transaction',
  'explorer.transactions': 'Transactions',
  'explorer.address': 'Address',
  'explorer.blockNumber': 'Block number',
  'explorer.blockHash': 'Block hash',
  'explorer.parentHash': 'Previous block hash',
  'explorer.timestamp': 'Time',
  'explorer.sequencer': 'Block producer',
  'explorer.transactionCount': 'Transactions in this block',
  'explorer.transactionHash': 'Transaction hash',
  'explorer.transactionType': 'What happened',
  'explorer.sender': 'Sent by',
  'explorer.nonce': 'Transaction sequence number',
  'explorer.fee': 'Fee paid',
  'explorer.finality': 'Network confirmation',
  'explorer.execution': 'Execution result',
  'explorer.revertReason': 'Why it failed',
  'explorer.contractClass': 'Contract class',
  'explorer.accountNonce': 'Account transaction count',
  'explorer.status': 'Status',
  'explorer.viewBlock': 'View block {number}',
  'explorer.viewTransaction': 'View transaction',
  'explorer.viewAddress': 'View address',
  'explorer.backHome': 'Back to explorer home',
  'explorer.noTransactions': 'This block contains no transactions.',
  'explorer.technicalDetails': 'Technical details',
  'explorer.technicalDetailsHelp': 'Raw blockchain data for developers and advanced users.',
  'explorer.copy': 'Copy {label}',
  'explorer.copied': 'Copied',
  'explorer.unknown': 'Not available',
  'explorer.status.succeeded': 'Succeeded',
  'explorer.status.reverted': 'Failed and reverted',
  'explorer.status.acceptedL2': 'Confirmed on SwapPulse',
  'explorer.status.acceptedL1': 'Confirmed and settled',
  'explorer.status.pending': 'Pending',
  'explorer.status.received': 'Received by the network',
  'explorer.status.rejected': 'Rejected',
  'explorer.type.invoke': 'A smart account or contract called another contract',
  'explorer.type.declare': 'A new smart-contract class was published',
  'explorer.type.deployAccount': 'A new smart account was created',
  'explorer.type.l1Handler': 'A message from another chain was processed',
  'explorer.type.unknown': 'Blockchain transaction',
  'explorer.error.invalid': 'That does not look like a valid block number or blockchain identifier.',
  'explorer.error.notFound': 'We could not find a matching block or transaction.',
  'explorer.error.transactionNotFound': 'That transaction could not be found.',
  'explorer.error.blockNotFound': 'That block could not be found.',
  'explorer.error.addressNotFound': 'That smart-contract address could not be found.',
  'explorer.error.unavailable': 'The explorer cannot reach the public SwapPulse blockchain right now. Please try again shortly.',
  'explorer.error.title': 'Explorer lookup failed',
  'explorer.directLinkHint': 'Share this page to link directly to this blockchain record.',
  'explorer.addressSummary': 'This is a deployed smart-contract or smart-account address on SwapPulse Testnet.',
  'explorer.blockSummary': 'A block is a group of transactions recorded together by the network.',
  'explorer.transactionSummary': 'A transaction is one recorded action submitted to the network.',
};

const es = {
  'nav.chainExplorer': 'Explorador de la cadena', 'nav.chainWallet': 'Cartera SwapPulse', 'footer.chainExplorer': 'Explorador de la cadena', 'footer.github': 'GitHub', 'footer.githubNewTab': 'Abrir el repositorio de SwapPulse en GitHub en una pestaña nueva', 'admin.publicExplorerUrl': 'URL pública del explorador',
  'lang.change': 'Cambiar idioma', 'lang.select': 'Seleccionar idioma',
  'explorer.seoTitle': 'Explorador de la cadena de SwapPulse', 'explorer.seoDescription': 'Explora bloques, transacciones y direcciones de contratos de SwapPulse Testnet con un lenguaje claro y sencillo.',
  'explorer.title': 'Explorador de la cadena de SwapPulse', 'explorer.networkBadge': 'SwapPulse Testnet', 'explorer.backToSwapPulse': 'Volver a SwapPulse', 'explorer.latestTransactions': 'Últimas transacciones', 'explorer.indexedActivity': 'Actividad indexada por SwapPulse', 'explorer.indexedActivityHelp': 'Hashes de transacciones públicas que SwapPulse ya ha vinculado a esta cuenta inteligente. Es un historial útil de la cartera, no un índice completo del archivo.', 'explorer.noIndexedActivity': 'Aún no hay transacciones indexadas por SwapPulse para esta dirección.', 'explorer.openWallet': 'Abrir la cartera SwapPulse', 'explorer.subtitle': 'Consulta lo que ocurre en SwapPulse Testnet sin necesidad de entender la jerga de blockchain.'
  'explorer.readOnlyNotice': 'Este explorador es de solo lectura. Muestra datos públicos de la cadena y no puede mover fondos ni cambiar tu cuenta.',
  'explorer.searchLabel': 'Buscar un bloque, una transacción o una dirección', 'explorer.searchPlaceholder': 'Introduce un número de bloque o un identificador 0x…',
  'explorer.searchHelp': 'Puedes pegar un número de bloque, hash de transacción, hash de bloque, dirección de contrato o un enlace completo del explorador de SwapPulse.', 'explorer.searchButton': 'Buscar', 'explorer.refresh': 'Actualizar', 'explorer.loading': 'Cargando datos de la cadena…',
  'explorer.latestBlocks': 'Bloques más recientes', 'explorer.latestBlock': 'Último bloque', 'explorer.chainId': 'ID de la cadena', 'explorer.rpcVersion': 'Versión RPC', 'explorer.network': 'Red',
  'explorer.block': 'Bloque', 'explorer.transaction': 'Transacción', 'explorer.transactions': 'Transacciones', 'explorer.address': 'Dirección', 'explorer.blockNumber': 'Número de bloque', 'explorer.blockHash': 'Hash del bloque', 'explorer.parentHash': 'Hash del bloque anterior', 'explorer.timestamp': 'Hora', 'explorer.sequencer': 'Productor del bloque', 'explorer.transactionCount': 'Transacciones en este bloque',
  'explorer.transactionHash': 'Hash de la transacción', 'explorer.transactionType': 'Qué ocurrió', 'explorer.sender': 'Enviado por', 'explorer.nonce': 'Número de secuencia de la transacción', 'explorer.fee': 'Comisión pagada', 'explorer.finality': 'Confirmación de la red', 'explorer.execution': 'Resultado de la ejecución', 'explorer.revertReason': 'Por qué falló', 'explorer.contractClass': 'Clase del contrato', 'explorer.accountNonce': 'Número de transacciones de la cuenta', 'explorer.status': 'Estado',
  'explorer.viewBlock': 'Ver bloque {number}', 'explorer.viewTransaction': 'Ver transacción', 'explorer.viewAddress': 'Ver dirección', 'explorer.backHome': 'Volver al inicio del explorador', 'explorer.noTransactions': 'Este bloque no contiene transacciones.', 'explorer.technicalDetails': 'Detalles técnicos', 'explorer.technicalDetailsHelp': 'Datos sin procesar de la cadena para desarrolladores y usuarios avanzados.', 'explorer.copy': 'Copiar {label}', 'explorer.copied': 'Copiado', 'explorer.unknown': 'No disponible',
  'explorer.status.succeeded': 'Correcta', 'explorer.status.reverted': 'Falló y se revirtió', 'explorer.status.acceptedL2': 'Confirmada en SwapPulse', 'explorer.status.acceptedL1': 'Confirmada y liquidada', 'explorer.status.pending': 'Pendiente', 'explorer.status.received': 'Recibida por la red', 'explorer.status.rejected': 'Rechazada',
  'explorer.type.invoke': 'Una cuenta inteligente o contrato llamó a otro contrato', 'explorer.type.declare': 'Se publicó una nueva clase de contrato inteligente', 'explorer.type.deployAccount': 'Se creó una nueva cuenta inteligente', 'explorer.type.l1Handler': 'Se procesó un mensaje de otra cadena', 'explorer.type.unknown': 'Transacción de blockchain',
  'explorer.error.invalid': 'Eso no parece un número de bloque ni un identificador de blockchain válido.', 'explorer.error.notFound': 'No encontramos ningún bloque o transacción que coincida.', 'explorer.error.transactionNotFound': 'No se encontró esa transacción.', 'explorer.error.blockNotFound': 'No se encontró ese bloque.', 'explorer.error.addressNotFound': 'No se encontró esa dirección de contrato inteligente.', 'explorer.error.unavailable': 'El explorador no puede acceder ahora mismo a la cadena pública de SwapPulse. Inténtalo de nuevo en breve.', 'explorer.error.title': 'Falló la búsqueda del explorador', 'explorer.directLinkHint': 'Comparte esta página para enlazar directamente a este registro de la cadena.', 'explorer.addressSummary': 'Esta es una dirección de contrato o cuenta inteligente desplegada en SwapPulse Testnet.', 'explorer.blockSummary': 'Un bloque es un grupo de transacciones registradas juntas por la red.', 'explorer.transactionSummary': 'Una transacción es una acción registrada enviada a la red.'
};

const fr = {
  'nav.chainExplorer': 'Explorateur de chaîne', 'nav.chainWallet': 'Portefeuille SwapPulse', 'footer.chainExplorer': 'Explorateur de chaîne', 'footer.github': 'GitHub', 'footer.githubNewTab': 'Ouvrir le dépôt GitHub de SwapPulse dans un nouvel onglet', 'admin.publicExplorerUrl': 'URL publique de l’explorateur', 'lang.change': 'Changer de langue', 'lang.select': 'Sélectionner la langue',
  'explorer.seoTitle': 'Explorateur de chaîne SwapPulse', 'explorer.seoDescription': 'Explorez les blocs, transactions et adresses de contrats de SwapPulse Testnet dans un langage clair et simple.', 'explorer.title': 'Explorateur de chaîne SwapPulse', 'explorer.networkBadge': 'SwapPulse Testnet', 'explorer.backToSwapPulse': 'Retour à SwapPulse', 'explorer.latestTransactions': 'Dernières transactions', 'explorer.indexedActivity': 'Activité indexée par SwapPulse', 'explorer.indexedActivityHelp': 'Hachages de transactions publiques déjà associés à ce compte intelligent par SwapPulse. Il s’agit d’un historique utile du portefeuille, pas d’un index complet des archives.', 'explorer.noIndexedActivity': 'Aucune transaction indexée par SwapPulse n’est encore disponible pour cette adresse.', 'explorer.openWallet': 'Ouvrir le portefeuille SwapPulse', 'explorer.subtitle': 'Découvrez ce qui se passe sur SwapPulse Testnet sans avoir à comprendre le jargon blockchain.' 'explorer.readOnlyNotice': 'Cet explorateur est en lecture seule. Il affiche des données publiques de la blockchain et ne peut ni déplacer des fonds ni modifier votre compte.',
  'explorer.searchLabel': 'Rechercher un bloc, une transaction ou une adresse', 'explorer.searchPlaceholder': 'Saisissez un numéro de bloc ou un identifiant 0x…', 'explorer.searchHelp': 'Vous pouvez coller un numéro de bloc, un hash de transaction, un hash de bloc, une adresse de contrat ou un lien complet de l’explorateur SwapPulse.', 'explorer.searchButton': 'Rechercher', 'explorer.refresh': 'Actualiser', 'explorer.loading': 'Chargement des données blockchain…', 'explorer.latestBlocks': 'Derniers blocs', 'explorer.latestBlock': 'Dernier bloc', 'explorer.chainId': 'ID de chaîne', 'explorer.rpcVersion': 'Version RPC', 'explorer.network': 'Réseau',
  'explorer.block': 'Bloc', 'explorer.transaction': 'Transaction', 'explorer.transactions': 'Transactions', 'explorer.address': 'Adresse', 'explorer.blockNumber': 'Numéro de bloc', 'explorer.blockHash': 'Hash du bloc', 'explorer.parentHash': 'Hash du bloc précédent', 'explorer.timestamp': 'Heure', 'explorer.sequencer': 'Producteur du bloc', 'explorer.transactionCount': 'Transactions dans ce bloc', 'explorer.transactionHash': 'Hash de transaction', 'explorer.transactionType': 'Ce qui s’est passé', 'explorer.sender': 'Envoyé par', 'explorer.nonce': 'Numéro de séquence de la transaction', 'explorer.fee': 'Frais payés', 'explorer.finality': 'Confirmation réseau', 'explorer.execution': 'Résultat de l’exécution', 'explorer.revertReason': 'Raison de l’échec', 'explorer.contractClass': 'Classe du contrat', 'explorer.accountNonce': 'Nombre de transactions du compte', 'explorer.status': 'Statut',
  'explorer.viewBlock': 'Voir le bloc {number}', 'explorer.viewTransaction': 'Voir la transaction', 'explorer.viewAddress': 'Voir l’adresse', 'explorer.backHome': 'Retour à l’accueil de l’explorateur', 'explorer.noTransactions': 'Ce bloc ne contient aucune transaction.', 'explorer.technicalDetails': 'Détails techniques', 'explorer.technicalDetailsHelp': 'Données blockchain brutes pour les développeurs et les utilisateurs avancés.', 'explorer.copy': 'Copier {label}', 'explorer.copied': 'Copié', 'explorer.unknown': 'Indisponible',
  'explorer.status.succeeded': 'Réussie', 'explorer.status.reverted': 'Échec avec annulation', 'explorer.status.acceptedL2': 'Confirmée sur SwapPulse', 'explorer.status.acceptedL1': 'Confirmée et réglée', 'explorer.status.pending': 'En attente', 'explorer.status.received': 'Reçue par le réseau', 'explorer.status.rejected': 'Rejetée',
  'explorer.type.invoke': 'Un compte intelligent ou un contrat a appelé un autre contrat', 'explorer.type.declare': 'Une nouvelle classe de contrat intelligent a été publiée', 'explorer.type.deployAccount': 'Un nouveau compte intelligent a été créé', 'explorer.type.l1Handler': 'Un message provenant d’une autre chaîne a été traité', 'explorer.type.unknown': 'Transaction blockchain',
  'explorer.error.invalid': 'Cela ne ressemble pas à un numéro de bloc ou à un identifiant blockchain valide.', 'explorer.error.notFound': 'Nous n’avons trouvé aucun bloc ni aucune transaction correspondant.', 'explorer.error.transactionNotFound': 'Cette transaction est introuvable.', 'explorer.error.blockNotFound': 'Ce bloc est introuvable.', 'explorer.error.addressNotFound': 'Cette adresse de contrat intelligent est introuvable.', 'explorer.error.unavailable': 'L’explorateur ne peut pas joindre la blockchain publique SwapPulse pour le moment. Réessayez bientôt.', 'explorer.error.title': 'Échec de la recherche', 'explorer.directLinkHint': 'Partagez cette page pour créer un lien direct vers cet enregistrement blockchain.', 'explorer.addressSummary': 'Il s’agit d’une adresse de contrat intelligent ou de compte intelligent déployée sur SwapPulse Testnet.', 'explorer.blockSummary': 'Un bloc est un groupe de transactions enregistrées ensemble par le réseau.', 'explorer.transactionSummary': 'Une transaction est une action enregistrée soumise au réseau.'
};

const de = {
  'nav.chainExplorer': 'Chain-Explorer', 'nav.chainWallet': 'SwapPulse-Wallet', 'footer.chainExplorer': 'Chain-Explorer', 'footer.github': 'GitHub', 'footer.githubNewTab': 'Das SwapPulse-GitHub-Repository in einem neuen Tab öffnen', 'admin.publicExplorerUrl': 'Öffentliche Explorer-URL', 'lang.change': 'Sprache ändern', 'lang.select': 'Sprache auswählen',
  'explorer.seoTitle': 'SwapPulse Chain-Explorer', 'explorer.seoDescription': 'Erkunde Blöcke, Transaktionen und Smart-Contract-Adressen im SwapPulse Testnet in klarer, verständlicher Sprache.', 'explorer.title': 'SwapPulse Chain-Explorer', 'explorer.networkBadge': 'SwapPulse Testnet', 'explorer.backToSwapPulse': 'Zurück zu SwapPulse', 'explorer.latestTransactions': 'Neueste Transaktionen', 'explorer.indexedActivity': 'Von SwapPulse indexierte Aktivität', 'explorer.indexedActivityHelp': 'Öffentliche Transaktions-Hashes, die SwapPulse bereits diesem Smart Account zugeordnet hat. Das ist ein nützlicher Wallet-Verlauf, aber kein vollständiger Archivindex.', 'explorer.noIndexedActivity': 'Für diese Adresse sind noch keine von SwapPulse indexierten Transaktionen verfügbar.', 'explorer.openWallet': 'SwapPulse-Wallet öffnen', 'explorer.subtitle': 'Sieh, was im SwapPulse Testnet passiert, ohne Blockchain-Fachbegriffe verstehen zu müssen.' 'explorer.readOnlyNotice': 'Dieser Explorer ist schreibgeschützt. Er zeigt öffentliche Blockchain-Daten und kann weder Guthaben bewegen noch dein Konto verändern.',
  'explorer.searchLabel': 'Block, Transaktion oder Adresse finden', 'explorer.searchPlaceholder': 'Blocknummer oder 0x…-Kennung eingeben', 'explorer.searchHelp': 'Du kannst eine Blocknummer, einen Transaktions-Hash, einen Block-Hash, eine Vertragsadresse oder einen vollständigen SwapPulse-Explorer-Link einfügen.', 'explorer.searchButton': 'Suchen', 'explorer.refresh': 'Aktualisieren', 'explorer.loading': 'Blockchain-Daten werden geladen…', 'explorer.latestBlocks': 'Neueste Blöcke', 'explorer.latestBlock': 'Neuester Block', 'explorer.chainId': 'Chain-ID', 'explorer.rpcVersion': 'RPC-Version', 'explorer.network': 'Netzwerk',
  'explorer.block': 'Block', 'explorer.transaction': 'Transaktion', 'explorer.transactions': 'Transaktionen', 'explorer.address': 'Adresse', 'explorer.blockNumber': 'Blocknummer', 'explorer.blockHash': 'Block-Hash', 'explorer.parentHash': 'Hash des vorherigen Blocks', 'explorer.timestamp': 'Zeit', 'explorer.sequencer': 'Block-Produzent', 'explorer.transactionCount': 'Transaktionen in diesem Block', 'explorer.transactionHash': 'Transaktions-Hash', 'explorer.transactionType': 'Was passiert ist', 'explorer.sender': 'Gesendet von', 'explorer.nonce': 'Transaktions-Reihenfolgenummer', 'explorer.fee': 'Bezahlte Gebühr', 'explorer.finality': 'Netzwerkbestätigung', 'explorer.execution': 'Ausführungsergebnis', 'explorer.revertReason': 'Grund des Fehlers', 'explorer.contractClass': 'Vertragsklasse', 'explorer.accountNonce': 'Transaktionszähler des Kontos', 'explorer.status': 'Status',
  'explorer.viewBlock': 'Block {number} anzeigen', 'explorer.viewTransaction': 'Transaktion anzeigen', 'explorer.viewAddress': 'Adresse anzeigen', 'explorer.backHome': 'Zur Explorer-Startseite', 'explorer.noTransactions': 'Dieser Block enthält keine Transaktionen.', 'explorer.technicalDetails': 'Technische Details', 'explorer.technicalDetailsHelp': 'Unverarbeitete Blockchain-Daten für Entwickler und fortgeschrittene Nutzer.', 'explorer.copy': '{label} kopieren', 'explorer.copied': 'Kopiert', 'explorer.unknown': 'Nicht verfügbar',
  'explorer.status.succeeded': 'Erfolgreich', 'explorer.status.reverted': 'Fehlgeschlagen und rückgängig gemacht', 'explorer.status.acceptedL2': 'Auf SwapPulse bestätigt', 'explorer.status.acceptedL1': 'Bestätigt und abgewickelt', 'explorer.status.pending': 'Ausstehend', 'explorer.status.received': 'Vom Netzwerk empfangen', 'explorer.status.rejected': 'Abgelehnt',
  'explorer.type.invoke': 'Ein Smart Account oder Vertrag hat einen anderen Vertrag aufgerufen', 'explorer.type.declare': 'Eine neue Smart-Contract-Klasse wurde veröffentlicht', 'explorer.type.deployAccount': 'Ein neuer Smart Account wurde erstellt', 'explorer.type.l1Handler': 'Eine Nachricht von einer anderen Chain wurde verarbeitet', 'explorer.type.unknown': 'Blockchain-Transaktion',
  'explorer.error.invalid': 'Das sieht nicht nach einer gültigen Blocknummer oder Blockchain-Kennung aus.', 'explorer.error.notFound': 'Kein passender Block und keine passende Transaktion gefunden.', 'explorer.error.transactionNotFound': 'Diese Transaktion wurde nicht gefunden.', 'explorer.error.blockNotFound': 'Dieser Block wurde nicht gefunden.', 'explorer.error.addressNotFound': 'Diese Smart-Contract-Adresse wurde nicht gefunden.', 'explorer.error.unavailable': 'Der Explorer kann die öffentliche SwapPulse-Blockchain derzeit nicht erreichen. Bitte versuche es gleich noch einmal.', 'explorer.error.title': 'Explorer-Suche fehlgeschlagen', 'explorer.directLinkHint': 'Teile diese Seite, um direkt auf diesen Blockchain-Eintrag zu verlinken.', 'explorer.addressSummary': 'Dies ist eine bereitgestellte Smart-Contract- oder Smart-Account-Adresse im SwapPulse Testnet.', 'explorer.blockSummary': 'Ein Block ist eine Gruppe von Transaktionen, die gemeinsam vom Netzwerk aufgezeichnet wurden.', 'explorer.transactionSummary': 'Eine Transaktion ist eine aufgezeichnete Aktion, die an das Netzwerk gesendet wurde.'
};

const it = {
  'nav.chainExplorer': 'Esplora blockchain', 'nav.chainWallet': 'Portafoglio SwapPulse', 'footer.chainExplorer': 'Esplora blockchain', 'footer.github': 'GitHub', 'footer.githubNewTab': 'Apri il repository GitHub di SwapPulse in una nuova scheda', 'admin.publicExplorerUrl': 'URL pubblica dell’explorer', 'lang.change': 'Cambia lingua', 'lang.select': 'Seleziona lingua',
  'explorer.seoTitle': 'Esplora blockchain SwapPulse', 'explorer.seoDescription': 'Esplora blocchi, transazioni e indirizzi di smart contract di SwapPulse Testnet con un linguaggio chiaro e semplice.', 'explorer.title': 'Esplora blockchain SwapPulse', 'explorer.networkBadge': 'SwapPulse Testnet', 'explorer.backToSwapPulse': 'Torna a SwapPulse', 'explorer.latestTransactions': 'Transazioni recenti', 'explorer.indexedActivity': 'Attività indicizzata da SwapPulse', 'explorer.indexedActivityHelp': 'Hash di transazioni pubbliche che SwapPulse ha già collegato a questo account intelligente. È una cronologia utile del portafoglio, non un indice completo dell’archivio.', 'explorer.noIndexedActivity': 'Non sono ancora disponibili transazioni indicizzate da SwapPulse per questo indirizzo.', 'explorer.openWallet': 'Apri il portafoglio SwapPulse', 'explorer.subtitle': 'Scopri cosa sta accadendo su SwapPulse Testnet senza dover conoscere il gergo blockchain.' 'explorer.readOnlyNotice': 'Questo explorer è di sola lettura. Mostra dati pubblici della blockchain e non può spostare fondi o modificare il tuo account.',
  'explorer.searchLabel': 'Trova un blocco, una transazione o un indirizzo', 'explorer.searchPlaceholder': 'Inserisci un numero di blocco o un identificatore 0x…', 'explorer.searchHelp': 'Puoi incollare un numero di blocco, hash di transazione, hash di blocco, indirizzo di contratto o un link completo dell’explorer SwapPulse.', 'explorer.searchButton': 'Cerca', 'explorer.refresh': 'Aggiorna', 'explorer.loading': 'Caricamento dei dati blockchain…', 'explorer.latestBlocks': 'Blocchi più recenti', 'explorer.latestBlock': 'Ultimo blocco', 'explorer.chainId': 'ID della chain', 'explorer.rpcVersion': 'Versione RPC', 'explorer.network': 'Rete',
  'explorer.block': 'Blocco', 'explorer.transaction': 'Transazione', 'explorer.transactions': 'Transazioni', 'explorer.address': 'Indirizzo', 'explorer.blockNumber': 'Numero del blocco', 'explorer.blockHash': 'Hash del blocco', 'explorer.parentHash': 'Hash del blocco precedente', 'explorer.timestamp': 'Ora', 'explorer.sequencer': 'Produttore del blocco', 'explorer.transactionCount': 'Transazioni in questo blocco', 'explorer.transactionHash': 'Hash della transazione', 'explorer.transactionType': 'Che cosa è successo', 'explorer.sender': 'Inviata da', 'explorer.nonce': 'Numero di sequenza della transazione', 'explorer.fee': 'Commissione pagata', 'explorer.finality': 'Conferma della rete', 'explorer.execution': 'Risultato dell’esecuzione', 'explorer.revertReason': 'Motivo dell’errore', 'explorer.contractClass': 'Classe del contratto', 'explorer.accountNonce': 'Numero di transazioni dell’account', 'explorer.status': 'Stato',
  'explorer.viewBlock': 'Visualizza blocco {number}', 'explorer.viewTransaction': 'Visualizza transazione', 'explorer.viewAddress': 'Visualizza indirizzo', 'explorer.backHome': 'Torna alla home dell’explorer', 'explorer.noTransactions': 'Questo blocco non contiene transazioni.', 'explorer.technicalDetails': 'Dettagli tecnici', 'explorer.technicalDetailsHelp': 'Dati blockchain grezzi per sviluppatori e utenti avanzati.', 'explorer.copy': 'Copia {label}', 'explorer.copied': 'Copiato', 'explorer.unknown': 'Non disponibile',
  'explorer.status.succeeded': 'Riuscita', 'explorer.status.reverted': 'Fallita e annullata', 'explorer.status.acceptedL2': 'Confermata su SwapPulse', 'explorer.status.acceptedL1': 'Confermata e regolata', 'explorer.status.pending': 'In attesa', 'explorer.status.received': 'Ricevuta dalla rete', 'explorer.status.rejected': 'Rifiutata',
  'explorer.type.invoke': 'Uno smart account o contratto ha chiamato un altro contratto', 'explorer.type.declare': 'È stata pubblicata una nuova classe di smart contract', 'explorer.type.deployAccount': 'È stato creato un nuovo smart account', 'explorer.type.l1Handler': 'È stato elaborato un messaggio proveniente da un’altra chain', 'explorer.type.unknown': 'Transazione blockchain',
  'explorer.error.invalid': 'Non sembra un numero di blocco o identificatore blockchain valido.', 'explorer.error.notFound': 'Non abbiamo trovato un blocco o una transazione corrispondente.', 'explorer.error.transactionNotFound': 'Questa transazione non è stata trovata.', 'explorer.error.blockNotFound': 'Questo blocco non è stato trovato.', 'explorer.error.addressNotFound': 'Questo indirizzo di smart contract non è stato trovato.', 'explorer.error.unavailable': 'L’explorer non riesce a raggiungere la blockchain pubblica SwapPulse in questo momento. Riprova tra poco.', 'explorer.error.title': 'Ricerca explorer non riuscita', 'explorer.directLinkHint': 'Condividi questa pagina per collegarti direttamente a questo record blockchain.', 'explorer.addressSummary': 'Questo è un indirizzo di smart contract o smart account distribuito su SwapPulse Testnet.', 'explorer.blockSummary': 'Un blocco è un gruppo di transazioni registrate insieme dalla rete.', 'explorer.transactionSummary': 'Una transazione è un’azione registrata inviata alla rete.'
};

const pt = {
  'nav.chainExplorer': 'Explorador da blockchain', 'nav.chainWallet': 'Carteira SwapPulse', 'footer.chainExplorer': 'Explorador da blockchain', 'footer.github': 'GitHub', 'footer.githubNewTab': 'Abrir o repositório GitHub do SwapPulse em uma nova aba', 'admin.publicExplorerUrl': 'URL pública do explorador', 'lang.change': 'Mudar idioma', 'lang.select': 'Selecionar idioma',
  'explorer.seoTitle': 'Explorador da blockchain SwapPulse', 'explorer.seoDescription': 'Explore blocos, transações e endereços de contratos da SwapPulse Testnet em linguagem clara e simples.', 'explorer.title': 'Explorador da blockchain SwapPulse', 'explorer.networkBadge': 'SwapPulse Testnet', 'explorer.backToSwapPulse': 'Voltar ao SwapPulse', 'explorer.latestTransactions': 'Transações recentes', 'explorer.indexedActivity': 'Atividade indexada pelo SwapPulse', 'explorer.indexedActivityHelp': 'Hashes de transações públicas que o SwapPulse já vinculou a esta conta inteligente. É um histórico útil da carteira, não um índice completo do arquivo.', 'explorer.noIndexedActivity': 'Ainda não há transações indexadas pelo SwapPulse para este endereço.', 'explorer.openWallet': 'Abrir a carteira SwapPulse', 'explorer.subtitle': 'Veja o que está acontecendo na SwapPulse Testnet sem precisar entender jargões de blockchain.' 'explorer.readOnlyNotice': 'Este explorador é somente leitura. Ele mostra dados públicos da blockchain e não pode mover fundos nem alterar sua conta.',
  'explorer.searchLabel': 'Encontrar um bloco, transação ou endereço', 'explorer.searchPlaceholder': 'Digite um número de bloco ou identificador 0x…', 'explorer.searchHelp': 'Você pode colar um número de bloco, hash de transação, hash de bloco, endereço de contrato ou um link completo do explorador SwapPulse.', 'explorer.searchButton': 'Buscar', 'explorer.refresh': 'Atualizar', 'explorer.loading': 'Carregando dados da blockchain…', 'explorer.latestBlocks': 'Blocos mais recentes', 'explorer.latestBlock': 'Bloco mais recente', 'explorer.chainId': 'ID da chain', 'explorer.rpcVersion': 'Versão RPC', 'explorer.network': 'Rede',
  'explorer.block': 'Bloco', 'explorer.transaction': 'Transação', 'explorer.transactions': 'Transações', 'explorer.address': 'Endereço', 'explorer.blockNumber': 'Número do bloco', 'explorer.blockHash': 'Hash do bloco', 'explorer.parentHash': 'Hash do bloco anterior', 'explorer.timestamp': 'Horário', 'explorer.sequencer': 'Produtor do bloco', 'explorer.transactionCount': 'Transações neste bloco', 'explorer.transactionHash': 'Hash da transação', 'explorer.transactionType': 'O que aconteceu', 'explorer.sender': 'Enviada por', 'explorer.nonce': 'Número de sequência da transação', 'explorer.fee': 'Taxa paga', 'explorer.finality': 'Confirmação da rede', 'explorer.execution': 'Resultado da execução', 'explorer.revertReason': 'Motivo da falha', 'explorer.contractClass': 'Classe do contrato', 'explorer.accountNonce': 'Contagem de transações da conta', 'explorer.status': 'Status',
  'explorer.viewBlock': 'Ver bloco {number}', 'explorer.viewTransaction': 'Ver transação', 'explorer.viewAddress': 'Ver endereço', 'explorer.backHome': 'Voltar ao início do explorador', 'explorer.noTransactions': 'Este bloco não contém transações.', 'explorer.technicalDetails': 'Detalhes técnicos', 'explorer.technicalDetailsHelp': 'Dados brutos da blockchain para desenvolvedores e usuários avançados.', 'explorer.copy': 'Copiar {label}', 'explorer.copied': 'Copiado', 'explorer.unknown': 'Não disponível',
  'explorer.status.succeeded': 'Concluída', 'explorer.status.reverted': 'Falhou e foi revertida', 'explorer.status.acceptedL2': 'Confirmada na SwapPulse', 'explorer.status.acceptedL1': 'Confirmada e liquidada', 'explorer.status.pending': 'Pendente', 'explorer.status.received': 'Recebida pela rede', 'explorer.status.rejected': 'Rejeitada',
  'explorer.type.invoke': 'Uma conta inteligente ou contrato chamou outro contrato', 'explorer.type.declare': 'Uma nova classe de smart contract foi publicada', 'explorer.type.deployAccount': 'Uma nova conta inteligente foi criada', 'explorer.type.l1Handler': 'Uma mensagem de outra chain foi processada', 'explorer.type.unknown': 'Transação blockchain',
  'explorer.error.invalid': 'Isso não parece um número de bloco ou identificador blockchain válido.', 'explorer.error.notFound': 'Não encontramos um bloco ou transação correspondente.', 'explorer.error.transactionNotFound': 'Essa transação não foi encontrada.', 'explorer.error.blockNotFound': 'Esse bloco não foi encontrado.', 'explorer.error.addressNotFound': 'Esse endereço de smart contract não foi encontrado.', 'explorer.error.unavailable': 'O explorador não consegue acessar a blockchain pública SwapPulse agora. Tente novamente em instantes.', 'explorer.error.title': 'Falha na busca do explorador', 'explorer.directLinkHint': 'Compartilhe esta página para criar um link direto para este registro da blockchain.', 'explorer.addressSummary': 'Este é um endereço de smart contract ou conta inteligente implantado na SwapPulse Testnet.', 'explorer.blockSummary': 'Um bloco é um grupo de transações registradas juntas pela rede.', 'explorer.transactionSummary': 'Uma transação é uma ação registrada enviada à rede.'
};

const ja = {
  'nav.chainExplorer': 'チェーンエクスプローラー', 'nav.chainWallet': 'SwapPulse ウォレット', 'footer.chainExplorer': 'チェーンエクスプローラー', 'footer.github': 'GitHub', 'footer.githubNewTab': 'SwapPulse の GitHub リポジトリを新しいタブで開く', 'admin.publicExplorerUrl': '公開エクスプローラーURL', 'lang.change': '言語を変更', 'lang.select': '言語を選択',
  'explorer.seoTitle': 'SwapPulse チェーンエクスプローラー', 'explorer.seoDescription': 'SwapPulse Testnet のブロック、トランザクション、スマートコントラクトアドレスを分かりやすい言葉で確認できます。', 'explorer.title': 'SwapPulse チェーンエクスプローラー', 'explorer.networkBadge': 'SwapPulse Testnet', 'explorer.backToSwapPulse': 'SwapPulse に戻る', 'explorer.latestTransactions': '最新トランザクション', 'explorer.indexedActivity': 'SwapPulse が索引化したアクティビティ', 'explorer.indexedActivityHelp': 'SwapPulse がこのスマートアカウントに既に関連付けた公開トランザクションハッシュです。便利なウォレット履歴ですが、完全なアーカイブ索引を意味するものではありません。', 'explorer.noIndexedActivity': 'このアドレスには、SwapPulse が索引化したトランザクションがまだありません。', 'explorer.openWallet': 'SwapPulse ウォレットを開く', 'explorer.subtitle': 'ブロックチェーン用語を知らなくても、SwapPulse Testnet で起きていることを確認できます。' 'explorer.readOnlyNotice': 'このエクスプローラーは読み取り専用です。公開ブロックチェーンデータを表示するだけで、資金の移動やアカウント変更はできません。',
  'explorer.searchLabel': 'ブロック、トランザクション、アドレスを検索', 'explorer.searchPlaceholder': 'ブロック番号または 0x… の識別子を入力', 'explorer.searchHelp': 'ブロック番号、トランザクションハッシュ、ブロックハッシュ、コントラクトアドレス、または SwapPulse エクスプローラーの完全なリンクを貼り付けられます。', 'explorer.searchButton': '検索', 'explorer.refresh': '更新', 'explorer.loading': 'ブロックチェーンデータを読み込み中…', 'explorer.latestBlocks': '最新ブロック', 'explorer.latestBlock': '最新ブロック', 'explorer.chainId': 'チェーンID', 'explorer.rpcVersion': 'RPCバージョン', 'explorer.network': 'ネットワーク',
  'explorer.block': 'ブロック', 'explorer.transaction': 'トランザクション', 'explorer.transactions': 'トランザクション', 'explorer.address': 'アドレス', 'explorer.blockNumber': 'ブロック番号', 'explorer.blockHash': 'ブロックハッシュ', 'explorer.parentHash': '前のブロックのハッシュ', 'explorer.timestamp': '時刻', 'explorer.sequencer': 'ブロック生成者', 'explorer.transactionCount': 'このブロックのトランザクション数', 'explorer.transactionHash': 'トランザクションハッシュ', 'explorer.transactionType': '実行された内容', 'explorer.sender': '送信元', 'explorer.nonce': 'トランザクション順序番号', 'explorer.fee': '支払った手数料', 'explorer.finality': 'ネットワーク確認', 'explorer.execution': '実行結果', 'explorer.revertReason': '失敗した理由', 'explorer.contractClass': 'コントラクトクラス', 'explorer.accountNonce': 'アカウントのトランザクション数', 'explorer.status': '状態',
  'explorer.viewBlock': 'ブロック {number} を表示', 'explorer.viewTransaction': 'トランザクションを表示', 'explorer.viewAddress': 'アドレスを表示', 'explorer.backHome': 'エクスプローラーのホームに戻る', 'explorer.noTransactions': 'このブロックにはトランザクションがありません。', 'explorer.technicalDetails': '技術的な詳細', 'explorer.technicalDetailsHelp': '開発者や上級ユーザー向けの生のブロックチェーンデータです。', 'explorer.copy': '{label}をコピー', 'explorer.copied': 'コピーしました', 'explorer.unknown': '利用できません',
  'explorer.status.succeeded': '成功', 'explorer.status.reverted': '失敗して取り消されました', 'explorer.status.acceptedL2': 'SwapPulseで確認済み', 'explorer.status.acceptedL1': '確認・確定済み', 'explorer.status.pending': '保留中', 'explorer.status.received': 'ネットワークが受信済み', 'explorer.status.rejected': '拒否されました',
  'explorer.type.invoke': 'スマートアカウントまたはコントラクトが別のコントラクトを呼び出しました', 'explorer.type.declare': '新しいスマートコントラクトクラスが公開されました', 'explorer.type.deployAccount': '新しいスマートアカウントが作成されました', 'explorer.type.l1Handler': '別チェーンからのメッセージが処理されました', 'explorer.type.unknown': 'ブロックチェーントランザクション',
  'explorer.error.invalid': '有効なブロック番号またはブロックチェーン識別子ではないようです。', 'explorer.error.notFound': '一致するブロックまたはトランザクションが見つかりませんでした。', 'explorer.error.transactionNotFound': 'そのトランザクションは見つかりませんでした。', 'explorer.error.blockNotFound': 'そのブロックは見つかりませんでした。', 'explorer.error.addressNotFound': 'そのスマートコントラクトアドレスは見つかりませんでした。', 'explorer.error.unavailable': '現在、公開 SwapPulse ブロックチェーンに接続できません。少ししてからもう一度お試しください。', 'explorer.error.title': 'エクスプローラー検索に失敗しました', 'explorer.directLinkHint': 'このページを共有すると、このブロックチェーン記録へ直接リンクできます。', 'explorer.addressSummary': 'これは SwapPulse Testnet にデプロイされたスマートコントラクトまたはスマートアカウントのアドレスです。', 'explorer.blockSummary': 'ブロックとは、ネットワークがまとめて記録したトランザクションのグループです。', 'explorer.transactionSummary': 'トランザクションとは、ネットワークに送信され記録された1つの操作です。'
};

const zh = {
  'nav.chainExplorer': '链上浏览器', 'nav.chainWallet': 'SwapPulse 钱包', 'footer.chainExplorer': '链上浏览器', 'footer.github': 'GitHub', 'footer.githubNewTab': '在新标签页中打开 SwapPulse GitHub 仓库', 'admin.publicExplorerUrl': '公开浏览器网址', 'lang.change': '更改语言', 'lang.select': '选择语言',
  'explorer.seoTitle': 'SwapPulse 链上浏览器', 'explorer.seoDescription': '用清晰易懂的语言查看 SwapPulse Testnet 的区块、交易和智能合约地址。', 'explorer.title': 'SwapPulse 链上浏览器', 'explorer.networkBadge': 'SwapPulse 测试网', 'explorer.backToSwapPulse': '返回 SwapPulse', 'explorer.latestTransactions': '最新交易', 'explorer.indexedActivity': 'SwapPulse 已索引活动', 'explorer.indexedActivityHelp': 'SwapPulse 已经与此智能账户关联的公开交易哈希。这是有用的钱包历史记录，但并不表示已经建立完整的归档索引。', 'explorer.noIndexedActivity': '此地址暂时没有可用的 SwapPulse 已索引交易。', 'explorer.openWallet': '打开 SwapPulse 钱包', 'explorer.subtitle': '无需了解区块链术语，也能看懂 SwapPulse Testnet 上正在发生什么。' 'explorer.readOnlyNotice': '此浏览器仅供查看。它只显示公开的区块链数据，不能转移资金或更改你的账户。',
  'explorer.searchLabel': '查找区块、交易或地址', 'explorer.searchPlaceholder': '输入区块号或 0x… 标识符', 'explorer.searchHelp': '你可以粘贴区块号、交易哈希、区块哈希、合约地址或完整的 SwapPulse 浏览器链接。', 'explorer.searchButton': '搜索', 'explorer.refresh': '刷新', 'explorer.loading': '正在加载区块链数据…', 'explorer.latestBlocks': '最新区块', 'explorer.latestBlock': '最新区块', 'explorer.chainId': '链 ID', 'explorer.rpcVersion': 'RPC 版本', 'explorer.network': '网络',
  'explorer.block': '区块', 'explorer.transaction': '交易', 'explorer.transactions': '交易', 'explorer.address': '地址', 'explorer.blockNumber': '区块号', 'explorer.blockHash': '区块哈希', 'explorer.parentHash': '上一个区块哈希', 'explorer.timestamp': '时间', 'explorer.sequencer': '区块生产者', 'explorer.transactionCount': '此区块中的交易数', 'explorer.transactionHash': '交易哈希', 'explorer.transactionType': '发生了什么', 'explorer.sender': '发送方', 'explorer.nonce': '交易序号', 'explorer.fee': '已支付费用', 'explorer.finality': '网络确认', 'explorer.execution': '执行结果', 'explorer.revertReason': '失败原因', 'explorer.contractClass': '合约类', 'explorer.accountNonce': '账户交易计数', 'explorer.status': '状态',
  'explorer.viewBlock': '查看区块 {number}', 'explorer.viewTransaction': '查看交易', 'explorer.viewAddress': '查看地址', 'explorer.backHome': '返回浏览器首页', 'explorer.noTransactions': '此区块不包含任何交易。', 'explorer.technicalDetails': '技术详情', 'explorer.technicalDetailsHelp': '供开发者和高级用户查看的原始区块链数据。', 'explorer.copy': '复制{label}', 'explorer.copied': '已复制', 'explorer.unknown': '不可用',
  'explorer.status.succeeded': '成功', 'explorer.status.reverted': '失败并已回滚', 'explorer.status.acceptedL2': '已在 SwapPulse 确认', 'explorer.status.acceptedL1': '已确认并结算', 'explorer.status.pending': '待处理', 'explorer.status.received': '网络已收到', 'explorer.status.rejected': '已拒绝',
  'explorer.type.invoke': '智能账户或合约调用了另一个合约', 'explorer.type.declare': '发布了新的智能合约类', 'explorer.type.deployAccount': '创建了新的智能账户', 'explorer.type.l1Handler': '处理了来自另一条链的消息', 'explorer.type.unknown': '区块链交易',
  'explorer.error.invalid': '这看起来不是有效的区块号或区块链标识符。', 'explorer.error.notFound': '未找到匹配的区块或交易。', 'explorer.error.transactionNotFound': '找不到该交易。', 'explorer.error.blockNotFound': '找不到该区块。', 'explorer.error.addressNotFound': '找不到该智能合约地址。', 'explorer.error.unavailable': '浏览器目前无法连接公开的 SwapPulse 区块链，请稍后再试。', 'explorer.error.title': '浏览器查询失败', 'explorer.directLinkHint': '分享此页面即可直接链接到这条区块链记录。', 'explorer.addressSummary': '这是部署在 SwapPulse Testnet 上的智能合约或智能账户地址。', 'explorer.blockSummary': '区块是网络一起记录的一组交易。', 'explorer.transactionSummary': '交易是提交到网络并被记录的一次操作。'
};

const ko = {
  'nav.chainExplorer': '체인 탐색기', 'nav.chainWallet': 'SwapPulse 지갑', 'footer.chainExplorer': '체인 탐색기', 'footer.github': 'GitHub', 'footer.githubNewTab': '새 탭에서 SwapPulse GitHub 저장소 열기', 'admin.publicExplorerUrl': '공개 탐색기 URL', 'lang.change': '언어 변경', 'lang.select': '언어 선택',
  'explorer.seoTitle': 'SwapPulse 체인 탐색기', 'explorer.seoDescription': 'SwapPulse Testnet의 블록, 트랜잭션, 스마트 컨트랙트 주소를 쉽고 명확한 표현으로 확인하세요.', 'explorer.title': 'SwapPulse 체인 탐색기', 'explorer.networkBadge': 'SwapPulse Testnet', 'explorer.backToSwapPulse': 'SwapPulse로 돌아가기', 'explorer.latestTransactions': '최신 트랜잭션', 'explorer.indexedActivity': 'SwapPulse 색인 활동', 'explorer.indexedActivityHelp': 'SwapPulse가 이 스마트 계정에 이미 연결한 공개 트랜잭션 해시입니다. 유용한 지갑 기록이지만 전체 아카이브 색인을 의미하지는 않습니다.', 'explorer.noIndexedActivity': '이 주소에는 아직 SwapPulse가 색인한 트랜잭션이 없습니다.', 'explorer.openWallet': 'SwapPulse 지갑 열기', 'explorer.subtitle': '블록체인 전문 용어를 몰라도 SwapPulse Testnet에서 일어나는 일을 확인할 수 있습니다.' 'explorer.readOnlyNotice': '이 탐색기는 읽기 전용입니다. 공개 블록체인 데이터만 보여 주며 자금을 이동하거나 계정을 변경할 수 없습니다.',
  'explorer.searchLabel': '블록, 트랜잭션 또는 주소 찾기', 'explorer.searchPlaceholder': '블록 번호 또는 0x… 식별자 입력', 'explorer.searchHelp': '블록 번호, 트랜잭션 해시, 블록 해시, 컨트랙트 주소 또는 전체 SwapPulse 탐색기 링크를 붙여넣을 수 있습니다.', 'explorer.searchButton': '검색', 'explorer.refresh': '새로고침', 'explorer.loading': '블록체인 데이터를 불러오는 중…', 'explorer.latestBlocks': '최신 블록', 'explorer.latestBlock': '최신 블록', 'explorer.chainId': '체인 ID', 'explorer.rpcVersion': 'RPC 버전', 'explorer.network': '네트워크',
  'explorer.block': '블록', 'explorer.transaction': '트랜잭션', 'explorer.transactions': '트랜잭션', 'explorer.address': '주소', 'explorer.blockNumber': '블록 번호', 'explorer.blockHash': '블록 해시', 'explorer.parentHash': '이전 블록 해시', 'explorer.timestamp': '시간', 'explorer.sequencer': '블록 생성자', 'explorer.transactionCount': '이 블록의 트랜잭션 수', 'explorer.transactionHash': '트랜잭션 해시', 'explorer.transactionType': '무슨 일이 있었나', 'explorer.sender': '보낸 주소', 'explorer.nonce': '트랜잭션 순서 번호', 'explorer.fee': '지불 수수료', 'explorer.finality': '네트워크 확인', 'explorer.execution': '실행 결과', 'explorer.revertReason': '실패 이유', 'explorer.contractClass': '컨트랙트 클래스', 'explorer.accountNonce': '계정 트랜잭션 수', 'explorer.status': '상태',
  'explorer.viewBlock': '블록 {number} 보기', 'explorer.viewTransaction': '트랜잭션 보기', 'explorer.viewAddress': '주소 보기', 'explorer.backHome': '탐색기 홈으로 돌아가기', 'explorer.noTransactions': '이 블록에는 트랜잭션이 없습니다.', 'explorer.technicalDetails': '기술 세부정보', 'explorer.technicalDetailsHelp': '개발자와 고급 사용자를 위한 원시 블록체인 데이터입니다.', 'explorer.copy': '{label} 복사', 'explorer.copied': '복사됨', 'explorer.unknown': '사용할 수 없음',
  'explorer.status.succeeded': '성공', 'explorer.status.reverted': '실패 후 되돌림', 'explorer.status.acceptedL2': 'SwapPulse에서 확인됨', 'explorer.status.acceptedL1': '확인 및 정산됨', 'explorer.status.pending': '대기 중', 'explorer.status.received': '네트워크가 수신함', 'explorer.status.rejected': '거부됨',
  'explorer.type.invoke': '스마트 계정 또는 컨트랙트가 다른 컨트랙트를 호출했습니다', 'explorer.type.declare': '새 스마트 컨트랙트 클래스가 게시되었습니다', 'explorer.type.deployAccount': '새 스마트 계정이 생성되었습니다', 'explorer.type.l1Handler': '다른 체인에서 온 메시지가 처리되었습니다', 'explorer.type.unknown': '블록체인 트랜잭션',
  'explorer.error.invalid': '유효한 블록 번호나 블록체인 식별자로 보이지 않습니다.', 'explorer.error.notFound': '일치하는 블록이나 트랜잭션을 찾지 못했습니다.', 'explorer.error.transactionNotFound': '해당 트랜잭션을 찾을 수 없습니다.', 'explorer.error.blockNotFound': '해당 블록을 찾을 수 없습니다.', 'explorer.error.addressNotFound': '해당 스마트 컨트랙트 주소를 찾을 수 없습니다.', 'explorer.error.unavailable': '현재 공개 SwapPulse 블록체인에 연결할 수 없습니다. 잠시 후 다시 시도해 주세요.', 'explorer.error.title': '탐색기 조회 실패', 'explorer.directLinkHint': '이 페이지를 공유하면 이 블록체인 기록으로 바로 연결됩니다.', 'explorer.addressSummary': 'SwapPulse Testnet에 배포된 스마트 컨트랙트 또는 스마트 계정 주소입니다.', 'explorer.blockSummary': '블록은 네트워크가 함께 기록한 트랜잭션 묶음입니다.', 'explorer.transactionSummary': '트랜잭션은 네트워크에 제출되어 기록된 하나의 작업입니다.'
};

export const explorerTranslations = {
  'en-GB': en,
  'es-ES': es,
  'fr-FR': fr,
  'de-DE': de,
  'it-IT': it,
  'pt-BR': pt,
  'ja-JP': ja,
  'zh-CN': zh,
  'ko-KR': ko,
};
